// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockAdminRepository is an autogenerated mock type for the AdminRepository type
type MockAdminRepository struct {
	mock.Mock
}

type MockAdminRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminRepository) EXPECT() *MockAdminRepository_Expecter {
	return &MockAdminRepository_Expecter{mock: &_m.Mock}
}

// AdjustGold provides a mock function with given fields: ctx, adminID, userID, amount, reason, ipAddress
func (_m *MockAdminRepository) AdjustGold(ctx context.Context, adminID uuid.UUID, userID uuid.UUID, amount int, reason string, ipAddress string) (*models.AdjustGoldResponse, error) {
	ret := _m.Called(ctx, adminID, userID, amount, reason, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for AdjustGold")
	}

	var r0 *models.AdjustGoldResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, string, string) (*models.AdjustGoldResponse, error)); ok {
		return rf(ctx, adminID, userID, amount, reason, ipAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, string, string) *models.AdjustGoldResponse); ok {
		r0 = rf(ctx, adminID, userID, amount, reason, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AdjustGoldResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, string, string) error); ok {
		r1 = rf(ctx, adminID, userID, amount, reason, ipAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_AdjustGold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdjustGold'
type MockAdminRepository_AdjustGold_Call struct {
	*mock.Call
}

// AdjustGold is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID uuid.UUID
//   - userID uuid.UUID
//   - amount int
//   - reason string
//   - ipAddress string
func (_e *MockAdminRepository_Expecter) AdjustGold(ctx interface{}, adminID interface{}, userID interface{}, amount interface{}, reason interface{}, ipAddress interface{}) *MockAdminRepository_AdjustGold_Call {
	return &MockAdminRepository_AdjustGold_Call{Call: _e.mock.On("AdjustGold", ctx, adminID, userID, amount, reason, ipAddress)}
}

func (_c *MockAdminRepository_AdjustGold_Call) Run(run func(ctx context.Context, adminID uuid.UUID, userID uuid.UUID, amount int, reason string, ipAddress string)) *MockAdminRepository_AdjustGold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockAdminRepository_AdjustGold_Call) Return(_a0 *models.AdjustGoldResponse, _a1 error) *MockAdminRepository_AdjustGold_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_AdjustGold_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int, string, string) (*models.AdjustGoldResponse, error)) *MockAdminRepository_AdjustGold_Call {
	_c.Call.Return(run)
	return _c
}

// BanUser provides a mock function with given fields: ctx, adminID, userID, reason, bannedUntil, ipAddress
func (_m *MockAdminRepository) BanUser(ctx context.Context, adminID uuid.UUID, userID uuid.UUID, reason string, bannedUntil *time.Time, ipAddress string) (*models.BanUserResponse, error) {
	ret := _m.Called(ctx, adminID, userID, reason, bannedUntil, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for BanUser")
	}

	var r0 *models.BanUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, *time.Time, string) (*models.BanUserResponse, error)); ok {
		return rf(ctx, adminID, userID, reason, bannedUntil, ipAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, *time.Time, string) *models.BanUserResponse); ok {
		r0 = rf(ctx, adminID, userID, reason, bannedUntil, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BanUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, *time.Time, string) error); ok {
		r1 = rf(ctx, adminID, userID, reason, bannedUntil, ipAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_BanUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BanUser'
type MockAdminRepository_BanUser_Call struct {
	*mock.Call
}

// BanUser is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID uuid.UUID
//   - userID uuid.UUID
//   - reason string
//   - bannedUntil *time.Time
//   - ipAddress string
func (_e *MockAdminRepository_Expecter) BanUser(ctx interface{}, adminID interface{}, userID interface{}, reason interface{}, bannedUntil interface{}, ipAddress interface{}) *MockAdminRepository_BanUser_Call {
	return &MockAdminRepository_BanUser_Call{Call: _e.mock.On("BanUser", ctx, adminID, userID, reason, bannedUntil, ipAddress)}
}

func (_c *MockAdminRepository_BanUser_Call) Run(run func(ctx context.Context, adminID uuid.UUID, userID uuid.UUID, reason string, bannedUntil *time.Time, ipAddress string)) *MockAdminRepository_BanUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(*time.Time), args[5].(string))
	})
	return _c
}

func (_c *MockAdminRepository_BanUser_Call) Return(_a0 *models.BanUserResponse, _a1 error) *MockAdminRepository_BanUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_BanUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, *time.Time, string) (*models.BanUserResponse, error)) *MockAdminRepository_BanUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetActions provides a mock function with given fields: ctx, page, perPage
func (_m *MockAdminRepository) GetActions(ctx context.Context, page int, perPage int) (*models.AdminActionsResponse, error) {
	ret := _m.Called(ctx, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for GetActions")
	}

	var r0 *models.AdminActionsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*models.AdminActionsResponse, error)); ok {
		return rf(ctx, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *models.AdminActionsResponse); ok {
		r0 = rf(ctx, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AdminActionsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_GetActions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActions'
type MockAdminRepository_GetActions_Call struct {
	*mock.Call
}

// GetActions is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - perPage int
func (_e *MockAdminRepository_Expecter) GetActions(ctx interface{}, page interface{}, perPage interface{}) *MockAdminRepository_GetActions_Call {
	return &MockAdminRepository_GetActions_Call{Call: _e.mock.On("GetActions", ctx, page, perPage)}
}

func (_c *MockAdminRepository_GetActions_Call) Run(run func(ctx context.Context, page int, perPage int)) *MockAdminRepository_GetActions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAdminRepository_GetActions_Call) Return(_a0 *models.AdminActionsResponse, _a1 error) *MockAdminRepository_GetActions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_GetActions_Call) RunAndReturn(run func(context.Context, int, int) (*models.AdminActionsResponse, error)) *MockAdminRepository_GetActions_Call {
	_c.Call.Return(run)
	return _c
}

// GetBanHistory provides a mock function with given fields: ctx, userID
func (_m *MockAdminRepository) GetBanHistory(ctx context.Context, userID uuid.UUID) ([]models.UserBan, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBanHistory")
	}

	var r0 []models.UserBan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.UserBan, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.UserBan); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserBan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_GetBanHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBanHistory'
type MockAdminRepository_GetBanHistory_Call struct {
	*mock.Call
}

// GetBanHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAdminRepository_Expecter) GetBanHistory(ctx interface{}, userID interface{}) *MockAdminRepository_GetBanHistory_Call {
	return &MockAdminRepository_GetBanHistory_Call{Call: _e.mock.On("GetBanHistory", ctx, userID)}
}

func (_c *MockAdminRepository_GetBanHistory_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAdminRepository_GetBanHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdminRepository_GetBanHistory_Call) Return(_a0 []models.UserBan, _a1 error) *MockAdminRepository_GetBanHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_GetBanHistory_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.UserBan, error)) *MockAdminRepository_GetBanHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetLevelCompletions provides a mock function with given fields: ctx, userID
func (_m *MockAdminRepository) GetLevelCompletions(ctx context.Context, userID uuid.UUID) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetLevelCompletions")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]map[string]interface{}, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []map[string]interface{}); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_GetLevelCompletions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLevelCompletions'
type MockAdminRepository_GetLevelCompletions_Call struct {
	*mock.Call
}

// GetLevelCompletions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAdminRepository_Expecter) GetLevelCompletions(ctx interface{}, userID interface{}) *MockAdminRepository_GetLevelCompletions_Call {
	return &MockAdminRepository_GetLevelCompletions_Call{Call: _e.mock.On("GetLevelCompletions", ctx, userID)}
}

func (_c *MockAdminRepository_GetLevelCompletions_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAdminRepository_GetLevelCompletions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdminRepository_GetLevelCompletions_Call) Return(_a0 []map[string]interface{}, _a1 error) *MockAdminRepository_GetLevelCompletions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_GetLevelCompletions_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]map[string]interface{}, error)) *MockAdminRepository_GetLevelCompletions_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function with given fields: ctx, userID
func (_m *MockAdminRepository) GetProfile(ctx context.Context, userID uuid.UUID) (*models.UserProfile, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *models.UserProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.UserProfile, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.UserProfile); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockAdminRepository_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAdminRepository_Expecter) GetProfile(ctx interface{}, userID interface{}) *MockAdminRepository_GetProfile_Call {
	return &MockAdminRepository_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, userID)}
}

func (_c *MockAdminRepository_GetProfile_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAdminRepository_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdminRepository_GetProfile_Call) Return(_a0 *models.UserProfile, _a1 error) *MockAdminRepository_GetProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_GetProfile_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.UserProfile, error)) *MockAdminRepository_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetSystemStats provides a mock function with given fields: ctx
func (_m *MockAdminRepository) GetSystemStats(ctx context.Context) (*models.SystemStatsResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSystemStats")
	}

	var r0 *models.SystemStatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.SystemStatsResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.SystemStatsResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SystemStatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_GetSystemStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSystemStats'
type MockAdminRepository_GetSystemStats_Call struct {
	*mock.Call
}

// GetSystemStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminRepository_Expecter) GetSystemStats(ctx interface{}) *MockAdminRepository_GetSystemStats_Call {
	return &MockAdminRepository_GetSystemStats_Call{Call: _e.mock.On("GetSystemStats", ctx)}
}

func (_c *MockAdminRepository_GetSystemStats_Call) Run(run func(ctx context.Context)) *MockAdminRepository_GetSystemStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAdminRepository_GetSystemStats_Call) Return(_a0 *models.SystemStatsResponse, _a1 error) *MockAdminRepository_GetSystemStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_GetSystemStats_Call) RunAndReturn(run func(context.Context) (*models.SystemStatsResponse, error)) *MockAdminRepository_GetSystemStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTalents provides a mock function with given fields: ctx, userID
func (_m *MockAdminRepository) GetUserTalents(ctx context.Context, userID uuid.UUID) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTalents")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]map[string]interface{}, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []map[string]interface{}); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_GetUserTalents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTalents'
type MockAdminRepository_GetUserTalents_Call struct {
	*mock.Call
}

// GetUserTalents is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAdminRepository_Expecter) GetUserTalents(ctx interface{}, userID interface{}) *MockAdminRepository_GetUserTalents_Call {
	return &MockAdminRepository_GetUserTalents_Call{Call: _e.mock.On("GetUserTalents", ctx, userID)}
}

func (_c *MockAdminRepository_GetUserTalents_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAdminRepository_GetUserTalents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdminRepository_GetUserTalents_Call) Return(_a0 []map[string]interface{}, _a1 error) *MockAdminRepository_GetUserTalents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_GetUserTalents_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]map[string]interface{}, error)) *MockAdminRepository_GetUserTalents_Call {
	_c.Call.Return(run)
	return _c
}

// LogAction provides a mock function with given fields: ctx, adminID, actionType, targetUserID, details, ipAddress
func (_m *MockAdminRepository) LogAction(ctx context.Context, adminID uuid.UUID, actionType string, targetUserID *uuid.UUID, details map[string]interface{}, ipAddress string) error {
	ret := _m.Called(ctx, adminID, actionType, targetUserID, details, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for LogAction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, *uuid.UUID, map[string]interface{}, string) error); ok {
		r0 = rf(ctx, adminID, actionType, targetUserID, details, ipAddress)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminRepository_LogAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogAction'
type MockAdminRepository_LogAction_Call struct {
	*mock.Call
}

// LogAction is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID uuid.UUID
//   - actionType string
//   - targetUserID *uuid.UUID
//   - details map[string]interface{}
//   - ipAddress string
func (_e *MockAdminRepository_Expecter) LogAction(ctx interface{}, adminID interface{}, actionType interface{}, targetUserID interface{}, details interface{}, ipAddress interface{}) *MockAdminRepository_LogAction_Call {
	return &MockAdminRepository_LogAction_Call{Call: _e.mock.On("LogAction", ctx, adminID, actionType, targetUserID, details, ipAddress)}
}

func (_c *MockAdminRepository_LogAction_Call) Run(run func(ctx context.Context, adminID uuid.UUID, actionType string, targetUserID *uuid.UUID, details map[string]interface{}, ipAddress string)) *MockAdminRepository_LogAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(*uuid.UUID), args[4].(map[string]interface{}), args[5].(string))
	})
	return _c
}

func (_c *MockAdminRepository_LogAction_Call) Return(_a0 error) *MockAdminRepository_LogAction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminRepository_LogAction_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, *uuid.UUID, map[string]interface{}, string) error) *MockAdminRepository_LogAction_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function with given fields: ctx, query, page, perPage
func (_m *MockAdminRepository) SearchUsers(ctx context.Context, query string, page int, perPage int) (*models.UserSearchResponse, error) {
	ret := _m.Called(ctx, query, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 *models.UserSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (*models.UserSearchResponse, error)); ok {
		return rf(ctx, query, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) *models.UserSearchResponse); ok {
		r0 = rf(ctx, query, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, query, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockAdminRepository_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - page int
//   - perPage int
func (_e *MockAdminRepository_Expecter) SearchUsers(ctx interface{}, query interface{}, page interface{}, perPage interface{}) *MockAdminRepository_SearchUsers_Call {
	return &MockAdminRepository_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, query, page, perPage)}
}

func (_c *MockAdminRepository_SearchUsers_Call) Run(run func(ctx context.Context, query string, page int, perPage int)) *MockAdminRepository_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockAdminRepository_SearchUsers_Call) Return(_a0 *models.UserSearchResponse, _a1 error) *MockAdminRepository_SearchUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_SearchUsers_Call) RunAndReturn(run func(context.Context, string, int, int) (*models.UserSearchResponse, error)) *MockAdminRepository_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UnbanUser provides a mock function with given fields: ctx, adminID, userID, reason, ipAddress
func (_m *MockAdminRepository) UnbanUser(ctx context.Context, adminID uuid.UUID, userID uuid.UUID, reason string, ipAddress string) (*models.UnbanUserResponse, error) {
	ret := _m.Called(ctx, adminID, userID, reason, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for UnbanUser")
	}

	var r0 *models.UnbanUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string) (*models.UnbanUserResponse, error)); ok {
		return rf(ctx, adminID, userID, reason, ipAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string) *models.UnbanUserResponse); ok {
		r0 = rf(ctx, adminID, userID, reason, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UnbanUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, adminID, userID, reason, ipAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_UnbanUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnbanUser'
type MockAdminRepository_UnbanUser_Call struct {
	*mock.Call
}

// UnbanUser is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID uuid.UUID
//   - userID uuid.UUID
//   - reason string
//   - ipAddress string
func (_e *MockAdminRepository_Expecter) UnbanUser(ctx interface{}, adminID interface{}, userID interface{}, reason interface{}, ipAddress interface{}) *MockAdminRepository_UnbanUser_Call {
	return &MockAdminRepository_UnbanUser_Call{Call: _e.mock.On("UnbanUser", ctx, adminID, userID, reason, ipAddress)}
}

func (_c *MockAdminRepository_UnbanUser_Call) Run(run func(ctx context.Context, adminID uuid.UUID, userID uuid.UUID, reason string, ipAddress string)) *MockAdminRepository_UnbanUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockAdminRepository_UnbanUser_Call) Return(_a0 *models.UnbanUserResponse, _a1 error) *MockAdminRepository_UnbanUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_UnbanUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, string) (*models.UnbanUserResponse, error)) *MockAdminRepository_UnbanUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminRepository creates a new instance of MockAdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminRepository {
	mock := &MockAdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
