// Code generated by mockery v2.53.6. DO NOT EDIT.

package repo_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// AnalyticsRepository is an autogenerated mock type for the AnalyticsRepository type
type AnalyticsRepository struct {
	mock.Mock
}

// RecordEvents provides a mock function with given fields: ctx, events
func (_m *AnalyticsRepository) RecordEvents(ctx context.Context, events []models.AnalyticsEvent) (int, int, error) {
	ret := _m.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for RecordEvents")
	}

	var r0 int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.AnalyticsEvent) (int, int, error)); ok {
		return rf(ctx, events)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.AnalyticsEvent) int); ok {
		r0 = rf(ctx, events)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.AnalyticsEvent) int); ok {
		r1 = rf(ctx, events)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, []models.AnalyticsEvent) error); ok {
		r2 = rf(ctx, events)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewAnalyticsRepository creates a new instance of AnalyticsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsRepository {
	mock := &AnalyticsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
