// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// MockAnalyticsRepository is an autogenerated mock type for the AnalyticsRepository type
type MockAnalyticsRepository struct {
	mock.Mock
}

type MockAnalyticsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalyticsRepository) EXPECT() *MockAnalyticsRepository_Expecter {
	return &MockAnalyticsRepository_Expecter{mock: &_m.Mock}
}

// RecordEvents provides a mock function with given fields: ctx, events
func (_m *MockAnalyticsRepository) RecordEvents(ctx context.Context, events []models.AnalyticsEvent) (int, int, error) {
	ret := _m.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for RecordEvents")
	}

	var r0 int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.AnalyticsEvent) (int, int, error)); ok {
		return rf(ctx, events)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.AnalyticsEvent) int); ok {
		r0 = rf(ctx, events)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.AnalyticsEvent) int); ok {
		r1 = rf(ctx, events)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, []models.AnalyticsEvent) error); ok {
		r2 = rf(ctx, events)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAnalyticsRepository_RecordEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordEvents'
type MockAnalyticsRepository_RecordEvents_Call struct {
	*mock.Call
}

// RecordEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - events []models.AnalyticsEvent
func (_e *MockAnalyticsRepository_Expecter) RecordEvents(ctx interface{}, events interface{}) *MockAnalyticsRepository_RecordEvents_Call {
	return &MockAnalyticsRepository_RecordEvents_Call{Call: _e.mock.On("RecordEvents", ctx, events)}
}

func (_c *MockAnalyticsRepository_RecordEvents_Call) Run(run func(ctx context.Context, events []models.AnalyticsEvent)) *MockAnalyticsRepository_RecordEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.AnalyticsEvent))
	})
	return _c
}

func (_c *MockAnalyticsRepository_RecordEvents_Call) Return(_a0 int, _a1 int, _a2 error) *MockAnalyticsRepository_RecordEvents_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAnalyticsRepository_RecordEvents_Call) RunAndReturn(run func(context.Context, []models.AnalyticsEvent) (int, int, error)) *MockAnalyticsRepository_RecordEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAnalyticsRepository creates a new instance of MockAnalyticsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyticsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyticsRepository {
	mock := &MockAnalyticsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
