// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository_mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIdentityRepository is an autogenerated mock type for the IdentityRepository type
type MockIdentityRepository struct {
	mock.Mock
}

type MockIdentityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdentityRepository) EXPECT() *MockIdentityRepository_Expecter {
	return &MockIdentityRepository_Expecter{mock: &_m.Mock}
}

// GetFriends provides a mock function with given fields: ctx, playfabID
func (_m *MockIdentityRepository) GetFriends(ctx context.Context, playfabID string) ([]string, error) {
	ret := _m.Called(ctx, playfabID)

	if len(ret) == 0 {
		panic("no return value specified for GetFriends")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, playfabID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, playfabID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, playfabID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdentityRepository_GetFriends_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFriends'
type MockIdentityRepository_GetFriends_Call struct {
	*mock.Call
}

// GetFriends is a helper method to define mock.On call
//   - ctx context.Context
//   - playfabID string
func (_e *MockIdentityRepository_Expecter) GetFriends(ctx interface{}, playfabID interface{}) *MockIdentityRepository_GetFriends_Call {
	return &MockIdentityRepository_GetFriends_Call{Call: _e.mock.On("GetFriends", ctx, playfabID)}
}

func (_c *MockIdentityRepository_GetFriends_Call) Run(run func(ctx context.Context, playfabID string)) *MockIdentityRepository_GetFriends_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIdentityRepository_GetFriends_Call) Return(_a0 []string, _a1 error) *MockIdentityRepository_GetFriends_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityRepository_GetFriends_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockIdentityRepository_GetFriends_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateTicket provides a mock function with given fields: ctx, sessionTicket
func (_m *MockIdentityRepository) ValidateTicket(ctx context.Context, sessionTicket string) (string, error) {
	ret := _m.Called(ctx, sessionTicket)

	if len(ret) == 0 {
		panic("no return value specified for ValidateTicket")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, sessionTicket)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, sessionTicket)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionTicket)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIdentityRepository_ValidateTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateTicket'
type MockIdentityRepository_ValidateTicket_Call struct {
	*mock.Call
}

// ValidateTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionTicket string
func (_e *MockIdentityRepository_Expecter) ValidateTicket(ctx interface{}, sessionTicket interface{}) *MockIdentityRepository_ValidateTicket_Call {
	return &MockIdentityRepository_ValidateTicket_Call{Call: _e.mock.On("ValidateTicket", ctx, sessionTicket)}
}

func (_c *MockIdentityRepository_ValidateTicket_Call) Run(run func(ctx context.Context, sessionTicket string)) *MockIdentityRepository_ValidateTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIdentityRepository_ValidateTicket_Call) Return(_a0 string, _a1 error) *MockIdentityRepository_ValidateTicket_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIdentityRepository_ValidateTicket_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockIdentityRepository_ValidateTicket_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdentityRepository creates a new instance of MockIdentityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdentityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdentityRepository {
	mock := &MockIdentityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
