// Code generated by mockery v2.53.6. DO NOT EDIT.

package repo_mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IdentityRepository is an autogenerated mock type for the IdentityRepository type
type IdentityRepository struct {
	mock.Mock
}

// ValidateTicket provides a mock function with given fields: ctx, sessionTicket
func (_m *IdentityRepository) ValidateTicket(ctx context.Context, sessionTicket string) (string, error) {
	ret := _m.Called(ctx, sessionTicket)

	if len(ret) == 0 {
		panic("no return value specified for ValidateTicket")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, sessionTicket)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, sessionTicket)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionTicket)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIdentityRepository creates a new instance of IdentityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityRepository {
	mock := &IdentityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
