// Code generated by mockery v2.53.6. DO NOT EDIT.

package repo_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// LeaderboardRepository is an autogenerated mock type for the LeaderboardRepository type
type LeaderboardRepository struct {
	mock.Mock
}

// GetByCriteria provides a mock function with given fields: ctx, lbType, scope, character, limit, offset
func (_m *LeaderboardRepository) GetByCriteria(ctx context.Context, lbType string, scope string, character string, limit int, offset int) ([]models.HollowWildsLeaderboardEntry, int, error) {
	ret := _m.Called(ctx, lbType, scope, character, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByCriteria")
	}

	var r0 []models.HollowWildsLeaderboardEntry
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) ([]models.HollowWildsLeaderboardEntry, int, error)); ok {
		return rf(ctx, lbType, scope, character, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) []models.HollowWildsLeaderboardEntry); ok {
		r0 = rf(ctx, lbType, scope, character, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.HollowWildsLeaderboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int, int) int); ok {
		r1 = rf(ctx, lbType, scope, character, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, int, int) error); ok {
		r2 = rf(ctx, lbType, scope, character, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetPersonalBest provides a mock function with given fields: ctx, playerID, lbType, character
func (_m *LeaderboardRepository) GetPersonalBest(ctx context.Context, playerID uuid.UUID, lbType string, character string) (int64, error) {
	ret := _m.Called(ctx, playerID, lbType, character)

	if len(ret) == 0 {
		panic("no return value specified for GetPersonalBest")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (int64, error)); ok {
		return rf(ctx, playerID, lbType, character)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) int64); ok {
		r0 = rf(ctx, playerID, lbType, character)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, playerID, lbType, character)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlayerStats provides a mock function with given fields: ctx, playerID
func (_m *LeaderboardRepository) GetPlayerStats(ctx context.Context, playerID uuid.UUID) ([]models.PlayerLeaderboardEntry, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayerStats")
	}

	var r0 []models.PlayerLeaderboardEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.PlayerLeaderboardEntry, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.PlayerLeaderboardEntry); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PlayerLeaderboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertEntry provides a mock function with given fields: ctx, entry
func (_m *LeaderboardRepository) UpsertEntry(ctx context.Context, entry *models.HollowWildsLeaderboardEntry) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for UpsertEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.HollowWildsLeaderboardEntry) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLeaderboardRepository creates a new instance of LeaderboardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeaderboardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeaderboardRepository {
	mock := &LeaderboardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
