// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockLeaderboardRepository is an autogenerated mock type for the LeaderboardRepository type
type MockLeaderboardRepository struct {
	mock.Mock
}

type MockLeaderboardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLeaderboardRepository) EXPECT() *MockLeaderboardRepository_Expecter {
	return &MockLeaderboardRepository_Expecter{mock: &_m.Mock}
}

// GetByCriteria provides a mock function with given fields: ctx, lbType, scope, character, limit, offset
func (_m *MockLeaderboardRepository) GetByCriteria(ctx context.Context, lbType string, scope string, character string, limit int, offset int) ([]models.HollowWildsLeaderboardEntry, int, error) {
	ret := _m.Called(ctx, lbType, scope, character, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByCriteria")
	}

	var r0 []models.HollowWildsLeaderboardEntry
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) ([]models.HollowWildsLeaderboardEntry, int, error)); ok {
		return rf(ctx, lbType, scope, character, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) []models.HollowWildsLeaderboardEntry); ok {
		r0 = rf(ctx, lbType, scope, character, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.HollowWildsLeaderboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int, int) int); ok {
		r1 = rf(ctx, lbType, scope, character, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, int, int) error); ok {
		r2 = rf(ctx, lbType, scope, character, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLeaderboardRepository_GetByCriteria_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCriteria'
type MockLeaderboardRepository_GetByCriteria_Call struct {
	*mock.Call
}

// GetByCriteria is a helper method to define mock.On call
//   - ctx context.Context
//   - lbType string
//   - scope string
//   - character string
//   - limit int
//   - offset int
func (_e *MockLeaderboardRepository_Expecter) GetByCriteria(ctx interface{}, lbType interface{}, scope interface{}, character interface{}, limit interface{}, offset interface{}) *MockLeaderboardRepository_GetByCriteria_Call {
	return &MockLeaderboardRepository_GetByCriteria_Call{Call: _e.mock.On("GetByCriteria", ctx, lbType, scope, character, limit, offset)}
}

func (_c *MockLeaderboardRepository_GetByCriteria_Call) Run(run func(ctx context.Context, lbType string, scope string, character string, limit int, offset int)) *MockLeaderboardRepository_GetByCriteria_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *MockLeaderboardRepository_GetByCriteria_Call) Return(_a0 []models.HollowWildsLeaderboardEntry, _a1 int, _a2 error) *MockLeaderboardRepository_GetByCriteria_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockLeaderboardRepository_GetByCriteria_Call) RunAndReturn(run func(context.Context, string, string, string, int, int) ([]models.HollowWildsLeaderboardEntry, int, error)) *MockLeaderboardRepository_GetByCriteria_Call {
	_c.Call.Return(run)
	return _c
}

// GetLegacyFriends provides a mock function with given fields: ctx, friendIDs, levelID
func (_m *MockLeaderboardRepository) GetLegacyFriends(ctx context.Context, friendIDs []string, levelID string) ([]models.LeaderboardEntry, error) {
	ret := _m.Called(ctx, friendIDs, levelID)

	if len(ret) == 0 {
		panic("no return value specified for GetLegacyFriends")
	}

	var r0 []models.LeaderboardEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) ([]models.LeaderboardEntry, error)); ok {
		return rf(ctx, friendIDs, levelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) []models.LeaderboardEntry); ok {
		r0 = rf(ctx, friendIDs, levelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.LeaderboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, string) error); ok {
		r1 = rf(ctx, friendIDs, levelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLeaderboardRepository_GetLegacyFriends_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLegacyFriends'
type MockLeaderboardRepository_GetLegacyFriends_Call struct {
	*mock.Call
}

// GetLegacyFriends is a helper method to define mock.On call
//   - ctx context.Context
//   - friendIDs []string
//   - levelID string
func (_e *MockLeaderboardRepository_Expecter) GetLegacyFriends(ctx interface{}, friendIDs interface{}, levelID interface{}) *MockLeaderboardRepository_GetLegacyFriends_Call {
	return &MockLeaderboardRepository_GetLegacyFriends_Call{Call: _e.mock.On("GetLegacyFriends", ctx, friendIDs, levelID)}
}

func (_c *MockLeaderboardRepository_GetLegacyFriends_Call) Run(run func(ctx context.Context, friendIDs []string, levelID string)) *MockLeaderboardRepository_GetLegacyFriends_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(string))
	})
	return _c
}

func (_c *MockLeaderboardRepository_GetLegacyFriends_Call) Return(_a0 []models.LeaderboardEntry, _a1 error) *MockLeaderboardRepository_GetLegacyFriends_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLeaderboardRepository_GetLegacyFriends_Call) RunAndReturn(run func(context.Context, []string, string) ([]models.LeaderboardEntry, error)) *MockLeaderboardRepository_GetLegacyFriends_Call {
	_c.Call.Return(run)
	return _c
}

// GetLegacyGlobal provides a mock function with given fields: ctx, levelID, limit, offset
func (_m *MockLeaderboardRepository) GetLegacyGlobal(ctx context.Context, levelID string, limit int, offset int) ([]models.LeaderboardEntry, int, error) {
	ret := _m.Called(ctx, levelID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetLegacyGlobal")
	}

	var r0 []models.LeaderboardEntry
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]models.LeaderboardEntry, int, error)); ok {
		return rf(ctx, levelID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []models.LeaderboardEntry); ok {
		r0 = rf(ctx, levelID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.LeaderboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, levelID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, levelID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLeaderboardRepository_GetLegacyGlobal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLegacyGlobal'
type MockLeaderboardRepository_GetLegacyGlobal_Call struct {
	*mock.Call
}

// GetLegacyGlobal is a helper method to define mock.On call
//   - ctx context.Context
//   - levelID string
//   - limit int
//   - offset int
func (_e *MockLeaderboardRepository_Expecter) GetLegacyGlobal(ctx interface{}, levelID interface{}, limit interface{}, offset interface{}) *MockLeaderboardRepository_GetLegacyGlobal_Call {
	return &MockLeaderboardRepository_GetLegacyGlobal_Call{Call: _e.mock.On("GetLegacyGlobal", ctx, levelID, limit, offset)}
}

func (_c *MockLeaderboardRepository_GetLegacyGlobal_Call) Run(run func(ctx context.Context, levelID string, limit int, offset int)) *MockLeaderboardRepository_GetLegacyGlobal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockLeaderboardRepository_GetLegacyGlobal_Call) Return(_a0 []models.LeaderboardEntry, _a1 int, _a2 error) *MockLeaderboardRepository_GetLegacyGlobal_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockLeaderboardRepository_GetLegacyGlobal_Call) RunAndReturn(run func(context.Context, string, int, int) ([]models.LeaderboardEntry, int, error)) *MockLeaderboardRepository_GetLegacyGlobal_Call {
	_c.Call.Return(run)
	return _c
}

// GetLegacyPlayerRank provides a mock function with given fields: ctx, userID, levelID
func (_m *MockLeaderboardRepository) GetLegacyPlayerRank(ctx context.Context, userID uuid.UUID, levelID string) (int, float64, int, error) {
	ret := _m.Called(ctx, userID, levelID)

	if len(ret) == 0 {
		panic("no return value specified for GetLegacyPlayerRank")
	}

	var r0 int
	var r1 float64
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (int, float64, int, error)); ok {
		return rf(ctx, userID, levelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) int); ok {
		r0 = rf(ctx, userID, levelID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) float64); ok {
		r1 = rf(ctx, userID, levelID)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string) int); ok {
		r2 = rf(ctx, userID, levelID)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, uuid.UUID, string) error); ok {
		r3 = rf(ctx, userID, levelID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockLeaderboardRepository_GetLegacyPlayerRank_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLegacyPlayerRank'
type MockLeaderboardRepository_GetLegacyPlayerRank_Call struct {
	*mock.Call
}

// GetLegacyPlayerRank is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - levelID string
func (_e *MockLeaderboardRepository_Expecter) GetLegacyPlayerRank(ctx interface{}, userID interface{}, levelID interface{}) *MockLeaderboardRepository_GetLegacyPlayerRank_Call {
	return &MockLeaderboardRepository_GetLegacyPlayerRank_Call{Call: _e.mock.On("GetLegacyPlayerRank", ctx, userID, levelID)}
}

func (_c *MockLeaderboardRepository_GetLegacyPlayerRank_Call) Run(run func(ctx context.Context, userID uuid.UUID, levelID string)) *MockLeaderboardRepository_GetLegacyPlayerRank_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockLeaderboardRepository_GetLegacyPlayerRank_Call) Return(_a0 int, _a1 float64, _a2 int, _a3 error) *MockLeaderboardRepository_GetLegacyPlayerRank_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockLeaderboardRepository_GetLegacyPlayerRank_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (int, float64, int, error)) *MockLeaderboardRepository_GetLegacyPlayerRank_Call {
	_c.Call.Return(run)
	return _c
}

// GetLegacyStats provides a mock function with given fields: ctx
func (_m *MockLeaderboardRepository) GetLegacyStats(ctx context.Context) (*models.LeaderboardStatsResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLegacyStats")
	}

	var r0 *models.LeaderboardStatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.LeaderboardStatsResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.LeaderboardStatsResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LeaderboardStatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLeaderboardRepository_GetLegacyStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLegacyStats'
type MockLeaderboardRepository_GetLegacyStats_Call struct {
	*mock.Call
}

// GetLegacyStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLeaderboardRepository_Expecter) GetLegacyStats(ctx interface{}) *MockLeaderboardRepository_GetLegacyStats_Call {
	return &MockLeaderboardRepository_GetLegacyStats_Call{Call: _e.mock.On("GetLegacyStats", ctx)}
}

func (_c *MockLeaderboardRepository_GetLegacyStats_Call) Run(run func(ctx context.Context)) *MockLeaderboardRepository_GetLegacyStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLeaderboardRepository_GetLegacyStats_Call) Return(_a0 *models.LeaderboardStatsResponse, _a1 error) *MockLeaderboardRepository_GetLegacyStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLeaderboardRepository_GetLegacyStats_Call) RunAndReturn(run func(context.Context) (*models.LeaderboardStatsResponse, error)) *MockLeaderboardRepository_GetLegacyStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetPersonalBest provides a mock function with given fields: ctx, playerID, lbType, character
func (_m *MockLeaderboardRepository) GetPersonalBest(ctx context.Context, playerID uuid.UUID, lbType string, character string) (int64, error) {
	ret := _m.Called(ctx, playerID, lbType, character)

	if len(ret) == 0 {
		panic("no return value specified for GetPersonalBest")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (int64, error)); ok {
		return rf(ctx, playerID, lbType, character)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) int64); ok {
		r0 = rf(ctx, playerID, lbType, character)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, playerID, lbType, character)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLeaderboardRepository_GetPersonalBest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPersonalBest'
type MockLeaderboardRepository_GetPersonalBest_Call struct {
	*mock.Call
}

// GetPersonalBest is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
//   - lbType string
//   - character string
func (_e *MockLeaderboardRepository_Expecter) GetPersonalBest(ctx interface{}, playerID interface{}, lbType interface{}, character interface{}) *MockLeaderboardRepository_GetPersonalBest_Call {
	return &MockLeaderboardRepository_GetPersonalBest_Call{Call: _e.mock.On("GetPersonalBest", ctx, playerID, lbType, character)}
}

func (_c *MockLeaderboardRepository_GetPersonalBest_Call) Run(run func(ctx context.Context, playerID uuid.UUID, lbType string, character string)) *MockLeaderboardRepository_GetPersonalBest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockLeaderboardRepository_GetPersonalBest_Call) Return(_a0 int64, _a1 error) *MockLeaderboardRepository_GetPersonalBest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLeaderboardRepository_GetPersonalBest_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) (int64, error)) *MockLeaderboardRepository_GetPersonalBest_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlayerStats provides a mock function with given fields: ctx, playerID
func (_m *MockLeaderboardRepository) GetPlayerStats(ctx context.Context, playerID uuid.UUID) ([]models.PlayerLeaderboardEntry, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayerStats")
	}

	var r0 []models.PlayerLeaderboardEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.PlayerLeaderboardEntry, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.PlayerLeaderboardEntry); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PlayerLeaderboardEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLeaderboardRepository_GetPlayerStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlayerStats'
type MockLeaderboardRepository_GetPlayerStats_Call struct {
	*mock.Call
}

// GetPlayerStats is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockLeaderboardRepository_Expecter) GetPlayerStats(ctx interface{}, playerID interface{}) *MockLeaderboardRepository_GetPlayerStats_Call {
	return &MockLeaderboardRepository_GetPlayerStats_Call{Call: _e.mock.On("GetPlayerStats", ctx, playerID)}
}

func (_c *MockLeaderboardRepository_GetPlayerStats_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockLeaderboardRepository_GetPlayerStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockLeaderboardRepository_GetPlayerStats_Call) Return(_a0 []models.PlayerLeaderboardEntry, _a1 error) *MockLeaderboardRepository_GetPlayerStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLeaderboardRepository_GetPlayerStats_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.PlayerLeaderboardEntry, error)) *MockLeaderboardRepository_GetPlayerStats_Call {
	_c.Call.Return(run)
	return _c
}

// ResetLegacyLeaderboard provides a mock function with given fields: ctx, levelID
func (_m *MockLeaderboardRepository) ResetLegacyLeaderboard(ctx context.Context, levelID string) error {
	ret := _m.Called(ctx, levelID)

	if len(ret) == 0 {
		panic("no return value specified for ResetLegacyLeaderboard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, levelID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLeaderboardRepository_ResetLegacyLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetLegacyLeaderboard'
type MockLeaderboardRepository_ResetLegacyLeaderboard_Call struct {
	*mock.Call
}

// ResetLegacyLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - levelID string
func (_e *MockLeaderboardRepository_Expecter) ResetLegacyLeaderboard(ctx interface{}, levelID interface{}) *MockLeaderboardRepository_ResetLegacyLeaderboard_Call {
	return &MockLeaderboardRepository_ResetLegacyLeaderboard_Call{Call: _e.mock.On("ResetLegacyLeaderboard", ctx, levelID)}
}

func (_c *MockLeaderboardRepository_ResetLegacyLeaderboard_Call) Run(run func(ctx context.Context, levelID string)) *MockLeaderboardRepository_ResetLegacyLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLeaderboardRepository_ResetLegacyLeaderboard_Call) Return(_a0 error) *MockLeaderboardRepository_ResetLegacyLeaderboard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLeaderboardRepository_ResetLegacyLeaderboard_Call) RunAndReturn(run func(context.Context, string) error) *MockLeaderboardRepository_ResetLegacyLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertEntry provides a mock function with given fields: ctx, entry
func (_m *MockLeaderboardRepository) UpsertEntry(ctx context.Context, entry *models.HollowWildsLeaderboardEntry) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for UpsertEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.HollowWildsLeaderboardEntry) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLeaderboardRepository_UpsertEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertEntry'
type MockLeaderboardRepository_UpsertEntry_Call struct {
	*mock.Call
}

// UpsertEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *models.HollowWildsLeaderboardEntry
func (_e *MockLeaderboardRepository_Expecter) UpsertEntry(ctx interface{}, entry interface{}) *MockLeaderboardRepository_UpsertEntry_Call {
	return &MockLeaderboardRepository_UpsertEntry_Call{Call: _e.mock.On("UpsertEntry", ctx, entry)}
}

func (_c *MockLeaderboardRepository_UpsertEntry_Call) Run(run func(ctx context.Context, entry *models.HollowWildsLeaderboardEntry)) *MockLeaderboardRepository_UpsertEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.HollowWildsLeaderboardEntry))
	})
	return _c
}

func (_c *MockLeaderboardRepository_UpsertEntry_Call) Return(_a0 error) *MockLeaderboardRepository_UpsertEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLeaderboardRepository_UpsertEntry_Call) RunAndReturn(run func(context.Context, *models.HollowWildsLeaderboardEntry) error) *MockLeaderboardRepository_UpsertEntry_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertLegacyEntry provides a mock function with given fields: ctx, userID, levelID, timeSeconds, stars
func (_m *MockLeaderboardRepository) UpsertLegacyEntry(ctx context.Context, userID uuid.UUID, levelID string, timeSeconds float64, stars int) error {
	ret := _m.Called(ctx, userID, levelID, timeSeconds, stars)

	if len(ret) == 0 {
		panic("no return value specified for UpsertLegacyEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, float64, int) error); ok {
		r0 = rf(ctx, userID, levelID, timeSeconds, stars)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLeaderboardRepository_UpsertLegacyEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertLegacyEntry'
type MockLeaderboardRepository_UpsertLegacyEntry_Call struct {
	*mock.Call
}

// UpsertLegacyEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - levelID string
//   - timeSeconds float64
//   - stars int
func (_e *MockLeaderboardRepository_Expecter) UpsertLegacyEntry(ctx interface{}, userID interface{}, levelID interface{}, timeSeconds interface{}, stars interface{}) *MockLeaderboardRepository_UpsertLegacyEntry_Call {
	return &MockLeaderboardRepository_UpsertLegacyEntry_Call{Call: _e.mock.On("UpsertLegacyEntry", ctx, userID, levelID, timeSeconds, stars)}
}

func (_c *MockLeaderboardRepository_UpsertLegacyEntry_Call) Run(run func(ctx context.Context, userID uuid.UUID, levelID string, timeSeconds float64, stars int)) *MockLeaderboardRepository_UpsertLegacyEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(float64), args[4].(int))
	})
	return _c
}

func (_c *MockLeaderboardRepository_UpsertLegacyEntry_Call) Return(_a0 error) *MockLeaderboardRepository_UpsertLegacyEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLeaderboardRepository_UpsertLegacyEntry_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, float64, int) error) *MockLeaderboardRepository_UpsertLegacyEntry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLeaderboardRepository creates a new instance of MockLeaderboardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLeaderboardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLeaderboardRepository {
	mock := &MockLeaderboardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
