// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockLevelRepository is an autogenerated mock type for the LevelRepository type
type MockLevelRepository struct {
	mock.Mock
}

type MockLevelRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLevelRepository) EXPECT() *MockLevelRepository_Expecter {
	return &MockLevelRepository_Expecter{mock: &_m.Mock}
}

// CreateCompletion provides a mock function with given fields: ctx, completion
func (_m *MockLevelRepository) CreateCompletion(ctx context.Context, completion *models.LevelCompletion) error {
	ret := _m.Called(ctx, completion)

	if len(ret) == 0 {
		panic("no return value specified for CreateCompletion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.LevelCompletion) error); ok {
		r0 = rf(ctx, completion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLevelRepository_CreateCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCompletion'
type MockLevelRepository_CreateCompletion_Call struct {
	*mock.Call
}

// CreateCompletion is a helper method to define mock.On call
//   - ctx context.Context
//   - completion *models.LevelCompletion
func (_e *MockLevelRepository_Expecter) CreateCompletion(ctx interface{}, completion interface{}) *MockLevelRepository_CreateCompletion_Call {
	return &MockLevelRepository_CreateCompletion_Call{Call: _e.mock.On("CreateCompletion", ctx, completion)}
}

func (_c *MockLevelRepository_CreateCompletion_Call) Run(run func(ctx context.Context, completion *models.LevelCompletion)) *MockLevelRepository_CreateCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.LevelCompletion))
	})
	return _c
}

func (_c *MockLevelRepository_CreateCompletion_Call) Return(_a0 error) *MockLevelRepository_CreateCompletion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLevelRepository_CreateCompletion_Call) RunAndReturn(run func(context.Context, *models.LevelCompletion) error) *MockLevelRepository_CreateCompletion_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompletion provides a mock function with given fields: ctx, userID, levelID
func (_m *MockLevelRepository) GetCompletion(ctx context.Context, userID uuid.UUID, levelID string) (*models.LevelCompletion, error) {
	ret := _m.Called(ctx, userID, levelID)

	if len(ret) == 0 {
		panic("no return value specified for GetCompletion")
	}

	var r0 *models.LevelCompletion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*models.LevelCompletion, error)); ok {
		return rf(ctx, userID, levelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *models.LevelCompletion); ok {
		r0 = rf(ctx, userID, levelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LevelCompletion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, levelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLevelRepository_GetCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompletion'
type MockLevelRepository_GetCompletion_Call struct {
	*mock.Call
}

// GetCompletion is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - levelID string
func (_e *MockLevelRepository_Expecter) GetCompletion(ctx interface{}, userID interface{}, levelID interface{}) *MockLevelRepository_GetCompletion_Call {
	return &MockLevelRepository_GetCompletion_Call{Call: _e.mock.On("GetCompletion", ctx, userID, levelID)}
}

func (_c *MockLevelRepository_GetCompletion_Call) Run(run func(ctx context.Context, userID uuid.UUID, levelID string)) *MockLevelRepository_GetCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockLevelRepository_GetCompletion_Call) Return(_a0 *models.LevelCompletion, _a1 error) *MockLevelRepository_GetCompletion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLevelRepository_GetCompletion_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*models.LevelCompletion, error)) *MockLevelRepository_GetCompletion_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function with given fields: ctx, levelID, mapID
func (_m *MockLevelRepository) GetConfig(ctx context.Context, levelID string, mapID string) (*models.LevelConfig, error) {
	ret := _m.Called(ctx, levelID, mapID)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 *models.LevelConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.LevelConfig, error)); ok {
		return rf(ctx, levelID, mapID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.LevelConfig); ok {
		r0 = rf(ctx, levelID, mapID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LevelConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, levelID, mapID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLevelRepository_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockLevelRepository_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - levelID string
//   - mapID string
func (_e *MockLevelRepository_Expecter) GetConfig(ctx interface{}, levelID interface{}, mapID interface{}) *MockLevelRepository_GetConfig_Call {
	return &MockLevelRepository_GetConfig_Call{Call: _e.mock.On("GetConfig", ctx, levelID, mapID)}
}

func (_c *MockLevelRepository_GetConfig_Call) Run(run func(ctx context.Context, levelID string, mapID string)) *MockLevelRepository_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockLevelRepository_GetConfig_Call) Return(_a0 *models.LevelConfig, _a1 error) *MockLevelRepository_GetConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLevelRepository_GetConfig_Call) RunAndReturn(run func(context.Context, string, string) (*models.LevelConfig, error)) *MockLevelRepository_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCompletion provides a mock function with given fields: ctx, completion
func (_m *MockLevelRepository) UpdateCompletion(ctx context.Context, completion *models.LevelCompletion) error {
	ret := _m.Called(ctx, completion)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCompletion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.LevelCompletion) error); ok {
		r0 = rf(ctx, completion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLevelRepository_UpdateCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCompletion'
type MockLevelRepository_UpdateCompletion_Call struct {
	*mock.Call
}

// UpdateCompletion is a helper method to define mock.On call
//   - ctx context.Context
//   - completion *models.LevelCompletion
func (_e *MockLevelRepository_Expecter) UpdateCompletion(ctx interface{}, completion interface{}) *MockLevelRepository_UpdateCompletion_Call {
	return &MockLevelRepository_UpdateCompletion_Call{Call: _e.mock.On("UpdateCompletion", ctx, completion)}
}

func (_c *MockLevelRepository_UpdateCompletion_Call) Run(run func(ctx context.Context, completion *models.LevelCompletion)) *MockLevelRepository_UpdateCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.LevelCompletion))
	})
	return _c
}

func (_c *MockLevelRepository_UpdateCompletion_Call) Return(_a0 error) *MockLevelRepository_UpdateCompletion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLevelRepository_UpdateCompletion_Call) RunAndReturn(run func(context.Context, *models.LevelCompletion) error) *MockLevelRepository_UpdateCompletion_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserStats provides a mock function with given fields: ctx, userID, goldEarned, starsEarned
func (_m *MockLevelRepository) UpdateUserStats(ctx context.Context, userID uuid.UUID, goldEarned int, starsEarned int) (int, int, error) {
	ret := _m.Called(ctx, userID, goldEarned, starsEarned)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserStats")
	}

	var r0 int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) (int, int, error)); ok {
		return rf(ctx, userID, goldEarned, starsEarned)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) int); ok {
		r0 = rf(ctx, userID, goldEarned, starsEarned)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, userID, goldEarned, starsEarned)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, userID, goldEarned, starsEarned)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLevelRepository_UpdateUserStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserStats'
type MockLevelRepository_UpdateUserStats_Call struct {
	*mock.Call
}

// UpdateUserStats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - goldEarned int
//   - starsEarned int
func (_e *MockLevelRepository_Expecter) UpdateUserStats(ctx interface{}, userID interface{}, goldEarned interface{}, starsEarned interface{}) *MockLevelRepository_UpdateUserStats_Call {
	return &MockLevelRepository_UpdateUserStats_Call{Call: _e.mock.On("UpdateUserStats", ctx, userID, goldEarned, starsEarned)}
}

func (_c *MockLevelRepository_UpdateUserStats_Call) Run(run func(ctx context.Context, userID uuid.UUID, goldEarned int, starsEarned int)) *MockLevelRepository_UpdateUserStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockLevelRepository_UpdateUserStats_Call) Return(_a0 int, _a1 int, _a2 error) *MockLevelRepository_UpdateUserStats_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockLevelRepository_UpdateUserStats_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) (int, int, error)) *MockLevelRepository_UpdateUserStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLevelRepository creates a new instance of MockLevelRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLevelRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLevelRepository {
	mock := &MockLevelRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
