// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPlayerRepository is an autogenerated mock type for the PlayerRepository type
type MockPlayerRepository struct {
	mock.Mock
}

type MockPlayerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlayerRepository) EXPECT() *MockPlayerRepository_Expecter {
	return &MockPlayerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, player
func (_m *MockPlayerRepository) Create(ctx context.Context, player *models.Player) error {
	ret := _m.Called(ctx, player)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Player) error); ok {
		r0 = rf(ctx, player)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPlayerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPlayerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - player *models.Player
func (_e *MockPlayerRepository_Expecter) Create(ctx interface{}, player interface{}) *MockPlayerRepository_Create_Call {
	return &MockPlayerRepository_Create_Call{Call: _e.mock.On("Create", ctx, player)}
}

func (_c *MockPlayerRepository_Create_Call) Run(run func(ctx context.Context, player *models.Player)) *MockPlayerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Player))
	})
	return _c
}

func (_c *MockPlayerRepository_Create_Call) Return(_a0 error) *MockPlayerRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayerRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Player) error) *MockPlayerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockPlayerRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Player, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Player
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Player, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Player); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Player)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlayerRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockPlayerRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockPlayerRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockPlayerRepository_GetByID_Call {
	return &MockPlayerRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockPlayerRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockPlayerRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPlayerRepository_GetByID_Call) Return(_a0 *models.Player, _a1 error) *MockPlayerRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlayerRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Player, error)) *MockPlayerRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPlayFabID provides a mock function with given fields: ctx, playfabID
func (_m *MockPlayerRepository) GetByPlayFabID(ctx context.Context, playfabID string) (*models.Player, error) {
	ret := _m.Called(ctx, playfabID)

	if len(ret) == 0 {
		panic("no return value specified for GetByPlayFabID")
	}

	var r0 *models.Player
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Player, error)); ok {
		return rf(ctx, playfabID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Player); ok {
		r0 = rf(ctx, playfabID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Player)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, playfabID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlayerRepository_GetByPlayFabID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPlayFabID'
type MockPlayerRepository_GetByPlayFabID_Call struct {
	*mock.Call
}

// GetByPlayFabID is a helper method to define mock.On call
//   - ctx context.Context
//   - playfabID string
func (_e *MockPlayerRepository_Expecter) GetByPlayFabID(ctx interface{}, playfabID interface{}) *MockPlayerRepository_GetByPlayFabID_Call {
	return &MockPlayerRepository_GetByPlayFabID_Call{Call: _e.mock.On("GetByPlayFabID", ctx, playfabID)}
}

func (_c *MockPlayerRepository_GetByPlayFabID_Call) Run(run func(ctx context.Context, playfabID string)) *MockPlayerRepository_GetByPlayFabID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPlayerRepository_GetByPlayFabID_Call) Return(_a0 *models.Player, _a1 error) *MockPlayerRepository_GetByPlayFabID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlayerRepository_GetByPlayFabID_Call) RunAndReturn(run func(context.Context, string) (*models.Player, error)) *MockPlayerRepository_GetByPlayFabID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastSeen provides a mock function with given fields: ctx, playerID
func (_m *MockPlayerRepository) UpdateLastSeen(ctx context.Context, playerID uuid.UUID) error {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastSeen")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPlayerRepository_UpdateLastSeen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastSeen'
type MockPlayerRepository_UpdateLastSeen_Call struct {
	*mock.Call
}

// UpdateLastSeen is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockPlayerRepository_Expecter) UpdateLastSeen(ctx interface{}, playerID interface{}) *MockPlayerRepository_UpdateLastSeen_Call {
	return &MockPlayerRepository_UpdateLastSeen_Call{Call: _e.mock.On("UpdateLastSeen", ctx, playerID)}
}

func (_c *MockPlayerRepository_UpdateLastSeen_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockPlayerRepository_UpdateLastSeen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPlayerRepository_UpdateLastSeen_Call) Return(_a0 error) *MockPlayerRepository_UpdateLastSeen_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayerRepository_UpdateLastSeen_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockPlayerRepository_UpdateLastSeen_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPlayerRepository creates a new instance of MockPlayerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlayerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlayerRepository {
	mock := &MockPlayerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
