// Code generated by mockery v2.53.6. DO NOT EDIT.

package repo_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlayerRepository is an autogenerated mock type for the PlayerRepository type
type PlayerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, player
func (_m *PlayerRepository) Create(ctx context.Context, player *models.Player) error {
	ret := _m.Called(ctx, player)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Player) error); ok {
		r0 = rf(ctx, player)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByPlayFabID provides a mock function with given fields: ctx, playfabID
func (_m *PlayerRepository) GetByPlayFabID(ctx context.Context, playfabID string) (*models.Player, error) {
	ret := _m.Called(ctx, playfabID)

	if len(ret) == 0 {
		panic("no return value specified for GetByPlayFabID")
	}

	var r0 *models.Player
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Player, error)); ok {
		return rf(ctx, playfabID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Player); ok {
		r0 = rf(ctx, playfabID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Player)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, playfabID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLastSeen provides a mock function with given fields: ctx, playerID
func (_m *PlayerRepository) UpdateLastSeen(ctx context.Context, playerID uuid.UUID) error {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastSeen")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPlayerRepository creates a new instance of PlayerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlayerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlayerRepository {
	mock := &PlayerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
