// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSaveRepository is an autogenerated mock type for the SaveRepository type
type MockSaveRepository struct {
	mock.Mock
}

type MockSaveRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSaveRepository) EXPECT() *MockSaveRepository_Expecter {
	return &MockSaveRepository_Expecter{mock: &_m.Mock}
}

// CountBackups provides a mock function with given fields: ctx, playerID
func (_m *MockSaveRepository) CountBackups(ctx context.Context, playerID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for CountBackups")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSaveRepository_CountBackups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountBackups'
type MockSaveRepository_CountBackups_Call struct {
	*mock.Call
}

// CountBackups is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockSaveRepository_Expecter) CountBackups(ctx interface{}, playerID interface{}) *MockSaveRepository_CountBackups_Call {
	return &MockSaveRepository_CountBackups_Call{Call: _e.mock.On("CountBackups", ctx, playerID)}
}

func (_c *MockSaveRepository_CountBackups_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockSaveRepository_CountBackups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSaveRepository_CountBackups_Call) Return(_a0 int, _a1 error) *MockSaveRepository_CountBackups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSaveRepository_CountBackups_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockSaveRepository_CountBackups_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBackup provides a mock function with given fields: ctx, backup
func (_m *MockSaveRepository) CreateBackup(ctx context.Context, backup *models.PlayerSaveBackup) error {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for CreateBackup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PlayerSaveBackup) error); ok {
		r0 = rf(ctx, backup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSaveRepository_CreateBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBackup'
type MockSaveRepository_CreateBackup_Call struct {
	*mock.Call
}

// CreateBackup is a helper method to define mock.On call
//   - ctx context.Context
//   - backup *models.PlayerSaveBackup
func (_e *MockSaveRepository_Expecter) CreateBackup(ctx interface{}, backup interface{}) *MockSaveRepository_CreateBackup_Call {
	return &MockSaveRepository_CreateBackup_Call{Call: _e.mock.On("CreateBackup", ctx, backup)}
}

func (_c *MockSaveRepository_CreateBackup_Call) Run(run func(ctx context.Context, backup *models.PlayerSaveBackup)) *MockSaveRepository_CreateBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.PlayerSaveBackup))
	})
	return _c
}

func (_c *MockSaveRepository_CreateBackup_Call) Return(_a0 error) *MockSaveRepository_CreateBackup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSaveRepository_CreateBackup_Call) RunAndReturn(run func(context.Context, *models.PlayerSaveBackup) error) *MockSaveRepository_CreateBackup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOldestBackup provides a mock function with given fields: ctx, playerID
func (_m *MockSaveRepository) DeleteOldestBackup(ctx context.Context, playerID uuid.UUID) error {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOldestBackup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSaveRepository_DeleteOldestBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOldestBackup'
type MockSaveRepository_DeleteOldestBackup_Call struct {
	*mock.Call
}

// DeleteOldestBackup is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockSaveRepository_Expecter) DeleteOldestBackup(ctx interface{}, playerID interface{}) *MockSaveRepository_DeleteOldestBackup_Call {
	return &MockSaveRepository_DeleteOldestBackup_Call{Call: _e.mock.On("DeleteOldestBackup", ctx, playerID)}
}

func (_c *MockSaveRepository_DeleteOldestBackup_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockSaveRepository_DeleteOldestBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSaveRepository_DeleteOldestBackup_Call) Return(_a0 error) *MockSaveRepository_DeleteOldestBackup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSaveRepository_DeleteOldestBackup_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockSaveRepository_DeleteOldestBackup_Call {
	_c.Call.Return(run)
	return _c
}

// GetBackupByID provides a mock function with given fields: ctx, backupID
func (_m *MockSaveRepository) GetBackupByID(ctx context.Context, backupID uuid.UUID) (*models.PlayerSaveBackup, error) {
	ret := _m.Called(ctx, backupID)

	if len(ret) == 0 {
		panic("no return value specified for GetBackupByID")
	}

	var r0 *models.PlayerSaveBackup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.PlayerSaveBackup, error)); ok {
		return rf(ctx, backupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.PlayerSaveBackup); ok {
		r0 = rf(ctx, backupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PlayerSaveBackup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, backupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSaveRepository_GetBackupByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBackupByID'
type MockSaveRepository_GetBackupByID_Call struct {
	*mock.Call
}

// GetBackupByID is a helper method to define mock.On call
//   - ctx context.Context
//   - backupID uuid.UUID
func (_e *MockSaveRepository_Expecter) GetBackupByID(ctx interface{}, backupID interface{}) *MockSaveRepository_GetBackupByID_Call {
	return &MockSaveRepository_GetBackupByID_Call{Call: _e.mock.On("GetBackupByID", ctx, backupID)}
}

func (_c *MockSaveRepository_GetBackupByID_Call) Run(run func(ctx context.Context, backupID uuid.UUID)) *MockSaveRepository_GetBackupByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSaveRepository_GetBackupByID_Call) Return(_a0 *models.PlayerSaveBackup, _a1 error) *MockSaveRepository_GetBackupByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSaveRepository_GetBackupByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.PlayerSaveBackup, error)) *MockSaveRepository_GetBackupByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBackupsByPlayerID provides a mock function with given fields: ctx, playerID
func (_m *MockSaveRepository) GetBackupsByPlayerID(ctx context.Context, playerID uuid.UUID) ([]models.PlayerSaveBackup, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetBackupsByPlayerID")
	}

	var r0 []models.PlayerSaveBackup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.PlayerSaveBackup, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.PlayerSaveBackup); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PlayerSaveBackup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSaveRepository_GetBackupsByPlayerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBackupsByPlayerID'
type MockSaveRepository_GetBackupsByPlayerID_Call struct {
	*mock.Call
}

// GetBackupsByPlayerID is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockSaveRepository_Expecter) GetBackupsByPlayerID(ctx interface{}, playerID interface{}) *MockSaveRepository_GetBackupsByPlayerID_Call {
	return &MockSaveRepository_GetBackupsByPlayerID_Call{Call: _e.mock.On("GetBackupsByPlayerID", ctx, playerID)}
}

func (_c *MockSaveRepository_GetBackupsByPlayerID_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockSaveRepository_GetBackupsByPlayerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSaveRepository_GetBackupsByPlayerID_Call) Return(_a0 []models.PlayerSaveBackup, _a1 error) *MockSaveRepository_GetBackupsByPlayerID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSaveRepository_GetBackupsByPlayerID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.PlayerSaveBackup, error)) *MockSaveRepository_GetBackupsByPlayerID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPlayerID provides a mock function with given fields: ctx, playerID
func (_m *MockSaveRepository) GetByPlayerID(ctx context.Context, playerID uuid.UUID) (*models.PlayerSave, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByPlayerID")
	}

	var r0 *models.PlayerSave
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.PlayerSave, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.PlayerSave); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PlayerSave)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSaveRepository_GetByPlayerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPlayerID'
type MockSaveRepository_GetByPlayerID_Call struct {
	*mock.Call
}

// GetByPlayerID is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockSaveRepository_Expecter) GetByPlayerID(ctx interface{}, playerID interface{}) *MockSaveRepository_GetByPlayerID_Call {
	return &MockSaveRepository_GetByPlayerID_Call{Call: _e.mock.On("GetByPlayerID", ctx, playerID)}
}

func (_c *MockSaveRepository_GetByPlayerID_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockSaveRepository_GetByPlayerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSaveRepository_GetByPlayerID_Call) Return(_a0 *models.PlayerSave, _a1 error) *MockSaveRepository_GetByPlayerID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSaveRepository_GetByPlayerID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.PlayerSave, error)) *MockSaveRepository_GetByPlayerID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, save
func (_m *MockSaveRepository) Upsert(ctx context.Context, save *models.PlayerSave) error {
	ret := _m.Called(ctx, save)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PlayerSave) error); ok {
		r0 = rf(ctx, save)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSaveRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockSaveRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - save *models.PlayerSave
func (_e *MockSaveRepository_Expecter) Upsert(ctx interface{}, save interface{}) *MockSaveRepository_Upsert_Call {
	return &MockSaveRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, save)}
}

func (_c *MockSaveRepository_Upsert_Call) Run(run func(ctx context.Context, save *models.PlayerSave)) *MockSaveRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.PlayerSave))
	})
	return _c
}

func (_c *MockSaveRepository_Upsert_Call) Return(_a0 error) *MockSaveRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSaveRepository_Upsert_Call) RunAndReturn(run func(context.Context, *models.PlayerSave) error) *MockSaveRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSaveRepository creates a new instance of MockSaveRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSaveRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSaveRepository {
	mock := &MockSaveRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
