// Code generated by mockery v2.53.6. DO NOT EDIT.

package repo_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// SaveRepository is an autogenerated mock type for the SaveRepository type
type SaveRepository struct {
	mock.Mock
}

// CountBackups provides a mock function with given fields: ctx, playerID
func (_m *SaveRepository) CountBackups(ctx context.Context, playerID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for CountBackups")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateBackup provides a mock function with given fields: ctx, backup
func (_m *SaveRepository) CreateBackup(ctx context.Context, backup *models.PlayerSaveBackup) error {
	ret := _m.Called(ctx, backup)

	if len(ret) == 0 {
		panic("no return value specified for CreateBackup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PlayerSaveBackup) error); ok {
		r0 = rf(ctx, backup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteOldestBackup provides a mock function with given fields: ctx, playerID
func (_m *SaveRepository) DeleteOldestBackup(ctx context.Context, playerID uuid.UUID) error {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOldestBackup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBackupsByPlayerID provides a mock function with given fields: ctx, playerID
func (_m *SaveRepository) GetBackupsByPlayerID(ctx context.Context, playerID uuid.UUID) ([]models.PlayerSaveBackup, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetBackupsByPlayerID")
	}

	var r0 []models.PlayerSaveBackup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.PlayerSaveBackup, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.PlayerSaveBackup); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PlayerSaveBackup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByPlayerID provides a mock function with given fields: ctx, playerID
func (_m *SaveRepository) GetByPlayerID(ctx context.Context, playerID uuid.UUID) (*models.PlayerSave, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByPlayerID")
	}

	var r0 *models.PlayerSave
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.PlayerSave, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.PlayerSave); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PlayerSave)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: ctx, save
func (_m *SaveRepository) Upsert(ctx context.Context, save *models.PlayerSave) error {
	ret := _m.Called(ctx, save)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PlayerSave) error); ok {
		r0 = rf(ctx, save)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSaveRepository creates a new instance of SaveRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSaveRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SaveRepository {
	mock := &SaveRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
