// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTalentRepository is an autogenerated mock type for the TalentRepository type
type MockTalentRepository struct {
	mock.Mock
}

type MockTalentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTalentRepository) EXPECT() *MockTalentRepository_Expecter {
	return &MockTalentRepository_Expecter{mock: &_m.Mock}
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MockTalentRepository) GetByUserID(ctx context.Context, userID uuid.UUID) ([]models.UserTalent, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []models.UserTalent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.UserTalent, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.UserTalent); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserTalent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTalentRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockTalentRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTalentRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockTalentRepository_GetByUserID_Call {
	return &MockTalentRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockTalentRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTalentRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTalentRepository_GetByUserID_Call) Return(_a0 []models.UserTalent, _a1 error) *MockTalentRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTalentRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.UserTalent, error)) *MockTalentRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfigs provides a mock function with given fields: ctx
func (_m *MockTalentRepository) GetConfigs(ctx context.Context) (map[string]*models.TalentConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConfigs")
	}

	var r0 map[string]*models.TalentConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]*models.TalentConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]*models.TalentConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*models.TalentConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTalentRepository_GetConfigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigs'
type MockTalentRepository_GetConfigs_Call struct {
	*mock.Call
}

// GetConfigs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTalentRepository_Expecter) GetConfigs(ctx interface{}) *MockTalentRepository_GetConfigs_Call {
	return &MockTalentRepository_GetConfigs_Call{Call: _e.mock.On("GetConfigs", ctx)}
}

func (_c *MockTalentRepository_GetConfigs_Call) Run(run func(ctx context.Context)) *MockTalentRepository_GetConfigs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTalentRepository_GetConfigs_Call) Return(_a0 map[string]*models.TalentConfig, _a1 error) *MockTalentRepository_GetConfigs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTalentRepository_GetConfigs_Call) RunAndReturn(run func(context.Context) (map[string]*models.TalentConfig, error)) *MockTalentRepository_GetConfigs_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreate provides a mock function with given fields: ctx, userID, talentID
func (_m *MockTalentRepository) GetOrCreate(ctx context.Context, userID uuid.UUID, talentID string) (*models.UserTalent, error) {
	ret := _m.Called(ctx, userID, talentID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *models.UserTalent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*models.UserTalent, error)); ok {
		return rf(ctx, userID, talentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *models.UserTalent); ok {
		r0 = rf(ctx, userID, talentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserTalent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, talentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTalentRepository_GetOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreate'
type MockTalentRepository_GetOrCreate_Call struct {
	*mock.Call
}

// GetOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - talentID string
func (_e *MockTalentRepository_Expecter) GetOrCreate(ctx interface{}, userID interface{}, talentID interface{}) *MockTalentRepository_GetOrCreate_Call {
	return &MockTalentRepository_GetOrCreate_Call{Call: _e.mock.On("GetOrCreate", ctx, userID, talentID)}
}

func (_c *MockTalentRepository_GetOrCreate_Call) Run(run func(ctx context.Context, userID uuid.UUID, talentID string)) *MockTalentRepository_GetOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockTalentRepository_GetOrCreate_Call) Return(_a0 *models.UserTalent, _a1 error) *MockTalentRepository_GetOrCreate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTalentRepository_GetOrCreate_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*models.UserTalent, error)) *MockTalentRepository_GetOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLevel provides a mock function with given fields: ctx, id, newLevel
func (_m *MockTalentRepository) UpdateLevel(ctx context.Context, id uuid.UUID, newLevel int) error {
	ret := _m.Called(ctx, id, newLevel)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLevel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) error); ok {
		r0 = rf(ctx, id, newLevel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTalentRepository_UpdateLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLevel'
type MockTalentRepository_UpdateLevel_Call struct {
	*mock.Call
}

// UpdateLevel is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - newLevel int
func (_e *MockTalentRepository_Expecter) UpdateLevel(ctx interface{}, id interface{}, newLevel interface{}) *MockTalentRepository_UpdateLevel_Call {
	return &MockTalentRepository_UpdateLevel_Call{Call: _e.mock.On("UpdateLevel", ctx, id, newLevel)}
}

func (_c *MockTalentRepository_UpdateLevel_Call) Run(run func(ctx context.Context, id uuid.UUID, newLevel int)) *MockTalentRepository_UpdateLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockTalentRepository_UpdateLevel_Call) Return(_a0 error) *MockTalentRepository_UpdateLevel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTalentRepository_UpdateLevel_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) error) *MockTalentRepository_UpdateLevel_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserGold provides a mock function with given fields: ctx, userID, goldChange
func (_m *MockTalentRepository) UpdateUserGold(ctx context.Context, userID uuid.UUID, goldChange int) (int, error) {
	ret := _m.Called(ctx, userID, goldChange)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserGold")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (int, error)); ok {
		return rf(ctx, userID, goldChange)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) int); ok {
		r0 = rf(ctx, userID, goldChange)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, userID, goldChange)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTalentRepository_UpdateUserGold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserGold'
type MockTalentRepository_UpdateUserGold_Call struct {
	*mock.Call
}

// UpdateUserGold is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - goldChange int
func (_e *MockTalentRepository_Expecter) UpdateUserGold(ctx interface{}, userID interface{}, goldChange interface{}) *MockTalentRepository_UpdateUserGold_Call {
	return &MockTalentRepository_UpdateUserGold_Call{Call: _e.mock.On("UpdateUserGold", ctx, userID, goldChange)}
}

func (_c *MockTalentRepository_UpdateUserGold_Call) Run(run func(ctx context.Context, userID uuid.UUID, goldChange int)) *MockTalentRepository_UpdateUserGold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockTalentRepository_UpdateUserGold_Call) Return(_a0 int, _a1 error) *MockTalentRepository_UpdateUserGold_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTalentRepository_UpdateUserGold_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) (int, error)) *MockTalentRepository_UpdateUserGold_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTalentRepository creates a new instance of MockTalentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTalentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTalentRepository {
	mock := &MockTalentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
