// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository_mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockTokenRepository is an autogenerated mock type for the TokenRepository type
type MockTokenRepository struct {
	mock.Mock
}

type MockTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepository) EXPECT() *MockTokenRepository_Expecter {
	return &MockTokenRepository_Expecter{mock: &_m.Mock}
}

// BlacklistJWT provides a mock function with given fields: ctx, jti, ttl
func (_m *MockTokenRepository) BlacklistJWT(ctx context.Context, jti string, ttl time.Duration) error {
	ret := _m.Called(ctx, jti, ttl)

	if len(ret) == 0 {
		panic("no return value specified for BlacklistJWT")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = rf(ctx, jti, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_BlacklistJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlacklistJWT'
type MockTokenRepository_BlacklistJWT_Call struct {
	*mock.Call
}

// BlacklistJWT is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
//   - ttl time.Duration
func (_e *MockTokenRepository_Expecter) BlacklistJWT(ctx interface{}, jti interface{}, ttl interface{}) *MockTokenRepository_BlacklistJWT_Call {
	return &MockTokenRepository_BlacklistJWT_Call{Call: _e.mock.On("BlacklistJWT", ctx, jti, ttl)}
}

func (_c *MockTokenRepository_BlacklistJWT_Call) Run(run func(ctx context.Context, jti string, ttl time.Duration)) *MockTokenRepository_BlacklistJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockTokenRepository_BlacklistJWT_Call) Return(_a0 error) *MockTokenRepository_BlacklistJWT_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_BlacklistJWT_Call) RunAndReturn(run func(context.Context, string, time.Duration) error) *MockTokenRepository_BlacklistJWT_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRefreshToken provides a mock function with given fields: ctx, token
func (_m *MockTokenRepository) DeleteRefreshToken(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_DeleteRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshToken'
type MockTokenRepository_DeleteRefreshToken_Call struct {
	*mock.Call
}

// DeleteRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenRepository_Expecter) DeleteRefreshToken(ctx interface{}, token interface{}) *MockTokenRepository_DeleteRefreshToken_Call {
	return &MockTokenRepository_DeleteRefreshToken_Call{Call: _e.mock.On("DeleteRefreshToken", ctx, token)}
}

func (_c *MockTokenRepository_DeleteRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockTokenRepository_DeleteRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepository_DeleteRefreshToken_Call) Return(_a0 error) *MockTokenRepository_DeleteRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_DeleteRefreshToken_Call) RunAndReturn(run func(context.Context, string) error) *MockTokenRepository_DeleteRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshToken provides a mock function with given fields: ctx, token
func (_m *MockTokenRepository) GetRefreshToken(ctx context.Context, token string) (string, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRepository_GetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshToken'
type MockTokenRepository_GetRefreshToken_Call struct {
	*mock.Call
}

// GetRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenRepository_Expecter) GetRefreshToken(ctx interface{}, token interface{}) *MockTokenRepository_GetRefreshToken_Call {
	return &MockTokenRepository_GetRefreshToken_Call{Call: _e.mock.On("GetRefreshToken", ctx, token)}
}

func (_c *MockTokenRepository_GetRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockTokenRepository_GetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepository_GetRefreshToken_Call) Return(_a0 string, _a1 error) *MockTokenRepository_GetRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepository_GetRefreshToken_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockTokenRepository_GetRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// IsJWTBlacklisted provides a mock function with given fields: ctx, jti
func (_m *MockTokenRepository) IsJWTBlacklisted(ctx context.Context, jti string) (bool, error) {
	ret := _m.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for IsJWTBlacklisted")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, jti)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, jti)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jti)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRepository_IsJWTBlacklisted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsJWTBlacklisted'
type MockTokenRepository_IsJWTBlacklisted_Call struct {
	*mock.Call
}

// IsJWTBlacklisted is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
func (_e *MockTokenRepository_Expecter) IsJWTBlacklisted(ctx interface{}, jti interface{}) *MockTokenRepository_IsJWTBlacklisted_Call {
	return &MockTokenRepository_IsJWTBlacklisted_Call{Call: _e.mock.On("IsJWTBlacklisted", ctx, jti)}
}

func (_c *MockTokenRepository_IsJWTBlacklisted_Call) Run(run func(ctx context.Context, jti string)) *MockTokenRepository_IsJWTBlacklisted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepository_IsJWTBlacklisted_Call) Return(_a0 bool, _a1 error) *MockTokenRepository_IsJWTBlacklisted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepository_IsJWTBlacklisted_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockTokenRepository_IsJWTBlacklisted_Call {
	_c.Call.Return(run)
	return _c
}

// StoreRefreshToken provides a mock function with given fields: ctx, token, userID, ttl
func (_m *MockTokenRepository) StoreRefreshToken(ctx context.Context, token string, userID string, ttl time.Duration) error {
	ret := _m.Called(ctx, token, userID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for StoreRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, token, userID, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_StoreRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreRefreshToken'
type MockTokenRepository_StoreRefreshToken_Call struct {
	*mock.Call
}

// StoreRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - userID string
//   - ttl time.Duration
func (_e *MockTokenRepository_Expecter) StoreRefreshToken(ctx interface{}, token interface{}, userID interface{}, ttl interface{}) *MockTokenRepository_StoreRefreshToken_Call {
	return &MockTokenRepository_StoreRefreshToken_Call{Call: _e.mock.On("StoreRefreshToken", ctx, token, userID, ttl)}
}

func (_c *MockTokenRepository_StoreRefreshToken_Call) Run(run func(ctx context.Context, token string, userID string, ttl time.Duration)) *MockTokenRepository_StoreRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockTokenRepository_StoreRefreshToken_Call) Return(_a0 error) *MockTokenRepository_StoreRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_StoreRefreshToken_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) error) *MockTokenRepository_StoreRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRepository creates a new instance of MockTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepository {
	mock := &MockTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
