// Code generated by mockery v2.53.6. DO NOT EDIT.

package usecase_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockAdminUsecase is an autogenerated mock type for the AdminUsecase type
type MockAdminUsecase struct {
	mock.Mock
}

type MockAdminUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminUsecase) EXPECT() *MockAdminUsecase_Expecter {
	return &MockAdminUsecase_Expecter{mock: &_m.Mock}
}

// AdjustGold provides a mock function with given fields: ctx, adminID, userID, amount, reason, ipAddress
func (_m *MockAdminUsecase) AdjustGold(ctx context.Context, adminID uuid.UUID, userID uuid.UUID, amount int, reason string, ipAddress string) (*models.AdjustGoldResponse, error) {
	ret := _m.Called(ctx, adminID, userID, amount, reason, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for AdjustGold")
	}

	var r0 *models.AdjustGoldResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, string, string) (*models.AdjustGoldResponse, error)); ok {
		return rf(ctx, adminID, userID, amount, reason, ipAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, string, string) *models.AdjustGoldResponse); ok {
		r0 = rf(ctx, adminID, userID, amount, reason, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AdjustGoldResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, string, string) error); ok {
		r1 = rf(ctx, adminID, userID, amount, reason, ipAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminUsecase_AdjustGold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdjustGold'
type MockAdminUsecase_AdjustGold_Call struct {
	*mock.Call
}

// AdjustGold is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID uuid.UUID
//   - userID uuid.UUID
//   - amount int
//   - reason string
//   - ipAddress string
func (_e *MockAdminUsecase_Expecter) AdjustGold(ctx interface{}, adminID interface{}, userID interface{}, amount interface{}, reason interface{}, ipAddress interface{}) *MockAdminUsecase_AdjustGold_Call {
	return &MockAdminUsecase_AdjustGold_Call{Call: _e.mock.On("AdjustGold", ctx, adminID, userID, amount, reason, ipAddress)}
}

func (_c *MockAdminUsecase_AdjustGold_Call) Run(run func(ctx context.Context, adminID uuid.UUID, userID uuid.UUID, amount int, reason string, ipAddress string)) *MockAdminUsecase_AdjustGold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockAdminUsecase_AdjustGold_Call) Return(_a0 *models.AdjustGoldResponse, _a1 error) *MockAdminUsecase_AdjustGold_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminUsecase_AdjustGold_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int, string, string) (*models.AdjustGoldResponse, error)) *MockAdminUsecase_AdjustGold_Call {
	_c.Call.Return(run)
	return _c
}

// BanUser provides a mock function with given fields: ctx, adminID, userID, reason, bannedUntil, ipAddress
func (_m *MockAdminUsecase) BanUser(ctx context.Context, adminID uuid.UUID, userID uuid.UUID, reason string, bannedUntil *time.Time, ipAddress string) (*models.BanUserResponse, error) {
	ret := _m.Called(ctx, adminID, userID, reason, bannedUntil, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for BanUser")
	}

	var r0 *models.BanUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, *time.Time, string) (*models.BanUserResponse, error)); ok {
		return rf(ctx, adminID, userID, reason, bannedUntil, ipAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, *time.Time, string) *models.BanUserResponse); ok {
		r0 = rf(ctx, adminID, userID, reason, bannedUntil, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BanUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, *time.Time, string) error); ok {
		r1 = rf(ctx, adminID, userID, reason, bannedUntil, ipAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminUsecase_BanUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BanUser'
type MockAdminUsecase_BanUser_Call struct {
	*mock.Call
}

// BanUser is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID uuid.UUID
//   - userID uuid.UUID
//   - reason string
//   - bannedUntil *time.Time
//   - ipAddress string
func (_e *MockAdminUsecase_Expecter) BanUser(ctx interface{}, adminID interface{}, userID interface{}, reason interface{}, bannedUntil interface{}, ipAddress interface{}) *MockAdminUsecase_BanUser_Call {
	return &MockAdminUsecase_BanUser_Call{Call: _e.mock.On("BanUser", ctx, adminID, userID, reason, bannedUntil, ipAddress)}
}

func (_c *MockAdminUsecase_BanUser_Call) Run(run func(ctx context.Context, adminID uuid.UUID, userID uuid.UUID, reason string, bannedUntil *time.Time, ipAddress string)) *MockAdminUsecase_BanUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(*time.Time), args[5].(string))
	})
	return _c
}

func (_c *MockAdminUsecase_BanUser_Call) Return(_a0 *models.BanUserResponse, _a1 error) *MockAdminUsecase_BanUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminUsecase_BanUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, *time.Time, string) (*models.BanUserResponse, error)) *MockAdminUsecase_BanUser_Call {
	_c.Call.Return(run)
	return _c
}

// ExportUserData provides a mock function with given fields: ctx, userID
func (_m *MockAdminUsecase) ExportUserData(ctx context.Context, userID uuid.UUID) (*models.ExportUserDataResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ExportUserData")
	}

	var r0 *models.ExportUserDataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.ExportUserDataResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.ExportUserDataResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ExportUserDataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminUsecase_ExportUserData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportUserData'
type MockAdminUsecase_ExportUserData_Call struct {
	*mock.Call
}

// ExportUserData is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAdminUsecase_Expecter) ExportUserData(ctx interface{}, userID interface{}) *MockAdminUsecase_ExportUserData_Call {
	return &MockAdminUsecase_ExportUserData_Call{Call: _e.mock.On("ExportUserData", ctx, userID)}
}

func (_c *MockAdminUsecase_ExportUserData_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAdminUsecase_ExportUserData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdminUsecase_ExportUserData_Call) Return(_a0 *models.ExportUserDataResponse, _a1 error) *MockAdminUsecase_ExportUserData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminUsecase_ExportUserData_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.ExportUserDataResponse, error)) *MockAdminUsecase_ExportUserData_Call {
	_c.Call.Return(run)
	return _c
}

// GetActions provides a mock function with given fields: ctx, page, perPage
func (_m *MockAdminUsecase) GetActions(ctx context.Context, page int, perPage int) (*models.AdminActionsResponse, error) {
	ret := _m.Called(ctx, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for GetActions")
	}

	var r0 *models.AdminActionsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*models.AdminActionsResponse, error)); ok {
		return rf(ctx, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *models.AdminActionsResponse); ok {
		r0 = rf(ctx, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AdminActionsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminUsecase_GetActions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActions'
type MockAdminUsecase_GetActions_Call struct {
	*mock.Call
}

// GetActions is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - perPage int
func (_e *MockAdminUsecase_Expecter) GetActions(ctx interface{}, page interface{}, perPage interface{}) *MockAdminUsecase_GetActions_Call {
	return &MockAdminUsecase_GetActions_Call{Call: _e.mock.On("GetActions", ctx, page, perPage)}
}

func (_c *MockAdminUsecase_GetActions_Call) Run(run func(ctx context.Context, page int, perPage int)) *MockAdminUsecase_GetActions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockAdminUsecase_GetActions_Call) Return(_a0 *models.AdminActionsResponse, _a1 error) *MockAdminUsecase_GetActions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminUsecase_GetActions_Call) RunAndReturn(run func(context.Context, int, int) (*models.AdminActionsResponse, error)) *MockAdminUsecase_GetActions_Call {
	_c.Call.Return(run)
	return _c
}

// GetBanHistory provides a mock function with given fields: ctx, userID
func (_m *MockAdminUsecase) GetBanHistory(ctx context.Context, userID uuid.UUID) ([]models.UserBan, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBanHistory")
	}

	var r0 []models.UserBan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.UserBan, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.UserBan); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserBan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminUsecase_GetBanHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBanHistory'
type MockAdminUsecase_GetBanHistory_Call struct {
	*mock.Call
}

// GetBanHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAdminUsecase_Expecter) GetBanHistory(ctx interface{}, userID interface{}) *MockAdminUsecase_GetBanHistory_Call {
	return &MockAdminUsecase_GetBanHistory_Call{Call: _e.mock.On("GetBanHistory", ctx, userID)}
}

func (_c *MockAdminUsecase_GetBanHistory_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAdminUsecase_GetBanHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdminUsecase_GetBanHistory_Call) Return(_a0 []models.UserBan, _a1 error) *MockAdminUsecase_GetBanHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminUsecase_GetBanHistory_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.UserBan, error)) *MockAdminUsecase_GetBanHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeaderboardStats provides a mock function with given fields: ctx
func (_m *MockAdminUsecase) GetLeaderboardStats(ctx context.Context) (*models.LeaderboardStatsResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaderboardStats")
	}

	var r0 *models.LeaderboardStatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.LeaderboardStatsResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.LeaderboardStatsResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LeaderboardStatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminUsecase_GetLeaderboardStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaderboardStats'
type MockAdminUsecase_GetLeaderboardStats_Call struct {
	*mock.Call
}

// GetLeaderboardStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminUsecase_Expecter) GetLeaderboardStats(ctx interface{}) *MockAdminUsecase_GetLeaderboardStats_Call {
	return &MockAdminUsecase_GetLeaderboardStats_Call{Call: _e.mock.On("GetLeaderboardStats", ctx)}
}

func (_c *MockAdminUsecase_GetLeaderboardStats_Call) Run(run func(ctx context.Context)) *MockAdminUsecase_GetLeaderboardStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAdminUsecase_GetLeaderboardStats_Call) Return(_a0 *models.LeaderboardStatsResponse, _a1 error) *MockAdminUsecase_GetLeaderboardStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminUsecase_GetLeaderboardStats_Call) RunAndReturn(run func(context.Context) (*models.LeaderboardStatsResponse, error)) *MockAdminUsecase_GetLeaderboardStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function with given fields: ctx, userID
func (_m *MockAdminUsecase) GetProfile(ctx context.Context, userID uuid.UUID) (*models.UserProfile, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *models.UserProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.UserProfile, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.UserProfile); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminUsecase_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockAdminUsecase_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAdminUsecase_Expecter) GetProfile(ctx interface{}, userID interface{}) *MockAdminUsecase_GetProfile_Call {
	return &MockAdminUsecase_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, userID)}
}

func (_c *MockAdminUsecase_GetProfile_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAdminUsecase_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdminUsecase_GetProfile_Call) Return(_a0 *models.UserProfile, _a1 error) *MockAdminUsecase_GetProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminUsecase_GetProfile_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.UserProfile, error)) *MockAdminUsecase_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetSystemStats provides a mock function with given fields: ctx
func (_m *MockAdminUsecase) GetSystemStats(ctx context.Context) (*models.SystemStatsResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSystemStats")
	}

	var r0 *models.SystemStatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.SystemStatsResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.SystemStatsResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SystemStatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminUsecase_GetSystemStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSystemStats'
type MockAdminUsecase_GetSystemStats_Call struct {
	*mock.Call
}

// GetSystemStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminUsecase_Expecter) GetSystemStats(ctx interface{}) *MockAdminUsecase_GetSystemStats_Call {
	return &MockAdminUsecase_GetSystemStats_Call{Call: _e.mock.On("GetSystemStats", ctx)}
}

func (_c *MockAdminUsecase_GetSystemStats_Call) Run(run func(ctx context.Context)) *MockAdminUsecase_GetSystemStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAdminUsecase_GetSystemStats_Call) Return(_a0 *models.SystemStatsResponse, _a1 error) *MockAdminUsecase_GetSystemStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminUsecase_GetSystemStats_Call) RunAndReturn(run func(context.Context) (*models.SystemStatsResponse, error)) *MockAdminUsecase_GetSystemStats_Call {
	_c.Call.Return(run)
	return _c
}

// ResetLeaderboard provides a mock function with given fields: ctx, adminID, levelID, reason, ipAddress
func (_m *MockAdminUsecase) ResetLeaderboard(ctx context.Context, adminID uuid.UUID, levelID string, reason string, ipAddress string) error {
	ret := _m.Called(ctx, adminID, levelID, reason, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for ResetLeaderboard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) error); ok {
		r0 = rf(ctx, adminID, levelID, reason, ipAddress)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminUsecase_ResetLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetLeaderboard'
type MockAdminUsecase_ResetLeaderboard_Call struct {
	*mock.Call
}

// ResetLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID uuid.UUID
//   - levelID string
//   - reason string
//   - ipAddress string
func (_e *MockAdminUsecase_Expecter) ResetLeaderboard(ctx interface{}, adminID interface{}, levelID interface{}, reason interface{}, ipAddress interface{}) *MockAdminUsecase_ResetLeaderboard_Call {
	return &MockAdminUsecase_ResetLeaderboard_Call{Call: _e.mock.On("ResetLeaderboard", ctx, adminID, levelID, reason, ipAddress)}
}

func (_c *MockAdminUsecase_ResetLeaderboard_Call) Run(run func(ctx context.Context, adminID uuid.UUID, levelID string, reason string, ipAddress string)) *MockAdminUsecase_ResetLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockAdminUsecase_ResetLeaderboard_Call) Return(_a0 error) *MockAdminUsecase_ResetLeaderboard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminUsecase_ResetLeaderboard_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, string) error) *MockAdminUsecase_ResetLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function with given fields: ctx, query, page, perPage
func (_m *MockAdminUsecase) SearchUsers(ctx context.Context, query string, page int, perPage int) (*models.UserSearchResponse, error) {
	ret := _m.Called(ctx, query, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 *models.UserSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (*models.UserSearchResponse, error)); ok {
		return rf(ctx, query, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) *models.UserSearchResponse); ok {
		r0 = rf(ctx, query, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserSearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, query, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminUsecase_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockAdminUsecase_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - page int
//   - perPage int
func (_e *MockAdminUsecase_Expecter) SearchUsers(ctx interface{}, query interface{}, page interface{}, perPage interface{}) *MockAdminUsecase_SearchUsers_Call {
	return &MockAdminUsecase_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, query, page, perPage)}
}

func (_c *MockAdminUsecase_SearchUsers_Call) Run(run func(ctx context.Context, query string, page int, perPage int)) *MockAdminUsecase_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockAdminUsecase_SearchUsers_Call) Return(_a0 *models.UserSearchResponse, _a1 error) *MockAdminUsecase_SearchUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminUsecase_SearchUsers_Call) RunAndReturn(run func(context.Context, string, int, int) (*models.UserSearchResponse, error)) *MockAdminUsecase_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UnbanUser provides a mock function with given fields: ctx, adminID, userID, reason, ipAddress
func (_m *MockAdminUsecase) UnbanUser(ctx context.Context, adminID uuid.UUID, userID uuid.UUID, reason string, ipAddress string) (*models.UnbanUserResponse, error) {
	ret := _m.Called(ctx, adminID, userID, reason, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for UnbanUser")
	}

	var r0 *models.UnbanUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string) (*models.UnbanUserResponse, error)); ok {
		return rf(ctx, adminID, userID, reason, ipAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string) *models.UnbanUserResponse); ok {
		r0 = rf(ctx, adminID, userID, reason, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UnbanUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, adminID, userID, reason, ipAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminUsecase_UnbanUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnbanUser'
type MockAdminUsecase_UnbanUser_Call struct {
	*mock.Call
}

// UnbanUser is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID uuid.UUID
//   - userID uuid.UUID
//   - reason string
//   - ipAddress string
func (_e *MockAdminUsecase_Expecter) UnbanUser(ctx interface{}, adminID interface{}, userID interface{}, reason interface{}, ipAddress interface{}) *MockAdminUsecase_UnbanUser_Call {
	return &MockAdminUsecase_UnbanUser_Call{Call: _e.mock.On("UnbanUser", ctx, adminID, userID, reason, ipAddress)}
}

func (_c *MockAdminUsecase_UnbanUser_Call) Run(run func(ctx context.Context, adminID uuid.UUID, userID uuid.UUID, reason string, ipAddress string)) *MockAdminUsecase_UnbanUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockAdminUsecase_UnbanUser_Call) Return(_a0 *models.UnbanUserResponse, _a1 error) *MockAdminUsecase_UnbanUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminUsecase_UnbanUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string, string) (*models.UnbanUserResponse, error)) *MockAdminUsecase_UnbanUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminUsecase creates a new instance of MockAdminUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminUsecase {
	mock := &MockAdminUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
