// Code generated by mockery v2.53.6. DO NOT EDIT.

package usecase_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAnalyticsUsecase is an autogenerated mock type for the AnalyticsUsecase type
type MockAnalyticsUsecase struct {
	mock.Mock
}

type MockAnalyticsUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalyticsUsecase) EXPECT() *MockAnalyticsUsecase_Expecter {
	return &MockAnalyticsUsecase_Expecter{mock: &_m.Mock}
}

// TrackEvents provides a mock function with given fields: ctx, playerID, events
func (_m *MockAnalyticsUsecase) TrackEvents(ctx context.Context, playerID *uuid.UUID, events []models.AnalyticsEvent) (int, int, error) {
	ret := _m.Called(ctx, playerID, events)

	if len(ret) == 0 {
		panic("no return value specified for TrackEvents")
	}

	var r0 int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID, []models.AnalyticsEvent) (int, int, error)); ok {
		return rf(ctx, playerID, events)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID, []models.AnalyticsEvent) int); ok {
		r0 = rf(ctx, playerID, events)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *uuid.UUID, []models.AnalyticsEvent) int); ok {
		r1 = rf(ctx, playerID, events)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *uuid.UUID, []models.AnalyticsEvent) error); ok {
		r2 = rf(ctx, playerID, events)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAnalyticsUsecase_TrackEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrackEvents'
type MockAnalyticsUsecase_TrackEvents_Call struct {
	*mock.Call
}

// TrackEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID *uuid.UUID
//   - events []models.AnalyticsEvent
func (_e *MockAnalyticsUsecase_Expecter) TrackEvents(ctx interface{}, playerID interface{}, events interface{}) *MockAnalyticsUsecase_TrackEvents_Call {
	return &MockAnalyticsUsecase_TrackEvents_Call{Call: _e.mock.On("TrackEvents", ctx, playerID, events)}
}

func (_c *MockAnalyticsUsecase_TrackEvents_Call) Run(run func(ctx context.Context, playerID *uuid.UUID, events []models.AnalyticsEvent)) *MockAnalyticsUsecase_TrackEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*uuid.UUID), args[2].([]models.AnalyticsEvent))
	})
	return _c
}

func (_c *MockAnalyticsUsecase_TrackEvents_Call) Return(_a0 int, _a1 int, _a2 error) *MockAnalyticsUsecase_TrackEvents_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAnalyticsUsecase_TrackEvents_Call) RunAndReturn(run func(context.Context, *uuid.UUID, []models.AnalyticsEvent) (int, int, error)) *MockAnalyticsUsecase_TrackEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAnalyticsUsecase creates a new instance of MockAnalyticsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyticsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyticsUsecase {
	mock := &MockAnalyticsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
