// Code generated by mockery v2.53.6. DO NOT EDIT.

package usecase_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AnalyticsUsecase is an autogenerated mock type for the AnalyticsUsecase type
type AnalyticsUsecase struct {
	mock.Mock
}

// TrackEvents provides a mock function with given fields: ctx, playerID, events
func (_m *AnalyticsUsecase) TrackEvents(ctx context.Context, playerID *uuid.UUID, events []models.AnalyticsEvent) (int, int, error) {
	ret := _m.Called(ctx, playerID, events)

	if len(ret) == 0 {
		panic("no return value specified for TrackEvents")
	}

	var r0 int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID, []models.AnalyticsEvent) (int, int, error)); ok {
		return rf(ctx, playerID, events)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID, []models.AnalyticsEvent) int); ok {
		r0 = rf(ctx, playerID, events)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *uuid.UUID, []models.AnalyticsEvent) int); ok {
		r1 = rf(ctx, playerID, events)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *uuid.UUID, []models.AnalyticsEvent) error); ok {
		r2 = rf(ctx, playerID, events)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewAnalyticsUsecase creates a new instance of AnalyticsUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsUsecase {
	mock := &AnalyticsUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
