// Code generated by mockery v2.53.6. DO NOT EDIT.

package usecase_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthUsecase is an autogenerated mock type for the AuthUsecase type
type MockAuthUsecase struct {
	mock.Mock
}

type MockAuthUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUsecase) EXPECT() *MockAuthUsecase_Expecter {
	return &MockAuthUsecase_Expecter{mock: &_m.Mock}
}

// LegacyLogin provides a mock function with given fields: ctx, playfabID, displayName, sessionToken
func (_m *MockAuthUsecase) LegacyLogin(ctx context.Context, playfabID string, displayName string, sessionToken string) (*models.AuthResponse, error) {
	ret := _m.Called(ctx, playfabID, displayName, sessionToken)

	if len(ret) == 0 {
		panic("no return value specified for LegacyLogin")
	}

	var r0 *models.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*models.AuthResponse, error)); ok {
		return rf(ctx, playfabID, displayName, sessionToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *models.AuthResponse); ok {
		r0 = rf(ctx, playfabID, displayName, sessionToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, playfabID, displayName, sessionToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthUsecase_LegacyLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LegacyLogin'
type MockAuthUsecase_LegacyLogin_Call struct {
	*mock.Call
}

// LegacyLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - playfabID string
//   - displayName string
//   - sessionToken string
func (_e *MockAuthUsecase_Expecter) LegacyLogin(ctx interface{}, playfabID interface{}, displayName interface{}, sessionToken interface{}) *MockAuthUsecase_LegacyLogin_Call {
	return &MockAuthUsecase_LegacyLogin_Call{Call: _e.mock.On("LegacyLogin", ctx, playfabID, displayName, sessionToken)}
}

func (_c *MockAuthUsecase_LegacyLogin_Call) Run(run func(ctx context.Context, playfabID string, displayName string, sessionToken string)) *MockAuthUsecase_LegacyLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthUsecase_LegacyLogin_Call) Return(_a0 *models.AuthResponse, _a1 error) *MockAuthUsecase_LegacyLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthUsecase_LegacyLogin_Call) RunAndReturn(run func(context.Context, string, string, string) (*models.AuthResponse, error)) *MockAuthUsecase_LegacyLogin_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, sessionTicket, overridePlayFabID
func (_m *MockAuthUsecase) Login(ctx context.Context, sessionTicket string, overridePlayFabID string) (*models.HollowWildsAuthResponse, error) {
	ret := _m.Called(ctx, sessionTicket, overridePlayFabID)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *models.HollowWildsAuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.HollowWildsAuthResponse, error)); ok {
		return rf(ctx, sessionTicket, overridePlayFabID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.HollowWildsAuthResponse); ok {
		r0 = rf(ctx, sessionTicket, overridePlayFabID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.HollowWildsAuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, sessionTicket, overridePlayFabID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthUsecase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthUsecase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionTicket string
//   - overridePlayFabID string
func (_e *MockAuthUsecase_Expecter) Login(ctx interface{}, sessionTicket interface{}, overridePlayFabID interface{}) *MockAuthUsecase_Login_Call {
	return &MockAuthUsecase_Login_Call{Call: _e.mock.On("Login", ctx, sessionTicket, overridePlayFabID)}
}

func (_c *MockAuthUsecase_Login_Call) Run(run func(ctx context.Context, sessionTicket string, overridePlayFabID string)) *MockAuthUsecase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthUsecase_Login_Call) Return(_a0 *models.HollowWildsAuthResponse, _a1 error) *MockAuthUsecase_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthUsecase_Login_Call) RunAndReturn(run func(context.Context, string, string) (*models.HollowWildsAuthResponse, error)) *MockAuthUsecase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, refreshToken, jti
func (_m *MockAuthUsecase) Logout(ctx context.Context, refreshToken string, jti string) error {
	ret := _m.Called(ctx, refreshToken, jti)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, refreshToken, jti)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthUsecase_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthUsecase_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
//   - jti string
func (_e *MockAuthUsecase_Expecter) Logout(ctx interface{}, refreshToken interface{}, jti interface{}) *MockAuthUsecase_Logout_Call {
	return &MockAuthUsecase_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken, jti)}
}

func (_c *MockAuthUsecase_Logout_Call) Run(run func(ctx context.Context, refreshToken string, jti string)) *MockAuthUsecase_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthUsecase_Logout_Call) Return(_a0 error) *MockAuthUsecase_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthUsecase_Logout_Call) RunAndReturn(run func(context.Context, string, string) error) *MockAuthUsecase_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *MockAuthUsecase) RefreshToken(ctx context.Context, refreshToken string) (*models.RefreshTokenResponse, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *models.RefreshTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.RefreshTokenResponse, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.RefreshTokenResponse); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RefreshTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthUsecase_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthUsecase_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthUsecase_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}) *MockAuthUsecase_RefreshToken_Call {
	return &MockAuthUsecase_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *MockAuthUsecase_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthUsecase_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthUsecase_RefreshToken_Call) Return(_a0 *models.RefreshTokenResponse, _a1 error) *MockAuthUsecase_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthUsecase_RefreshToken_Call) RunAndReturn(run func(context.Context, string) (*models.RefreshTokenResponse, error)) *MockAuthUsecase_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthUsecase creates a new instance of MockAuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUsecase {
	mock := &MockAuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
