// Code generated by mockery v2.53.6. DO NOT EDIT.

package usecase_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// AuthUsecase is an autogenerated mock type for the AuthUsecase type
type AuthUsecase struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, sessionTicket, overridePlayFabID
func (_m *AuthUsecase) Login(ctx context.Context, sessionTicket string, overridePlayFabID string) (*models.HollowWildsAuthResponse, error) {
	ret := _m.Called(ctx, sessionTicket, overridePlayFabID)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *models.HollowWildsAuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.HollowWildsAuthResponse, error)); ok {
		return rf(ctx, sessionTicket, overridePlayFabID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.HollowWildsAuthResponse); ok {
		r0 = rf(ctx, sessionTicket, overridePlayFabID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.HollowWildsAuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, sessionTicket, overridePlayFabID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: ctx, refreshToken, jti
func (_m *AuthUsecase) Logout(ctx context.Context, refreshToken string, jti string) error {
	ret := _m.Called(ctx, refreshToken, jti)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, refreshToken, jti)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshToken provides a mock function with given fields: ctx, refreshToken
func (_m *AuthUsecase) RefreshToken(ctx context.Context, refreshToken string) (*models.RefreshTokenResponse, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *models.RefreshTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.RefreshTokenResponse, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.RefreshTokenResponse); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RefreshTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthUsecase creates a new instance of AuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUsecase {
	mock := &AuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
