// Code generated by mockery v2.53.6. DO NOT EDIT.

package usecase_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// LeaderboardUsecase is an autogenerated mock type for the LeaderboardUsecase type
type LeaderboardUsecase struct {
	mock.Mock
}

// GetLeaderboard provides a mock function with given fields: ctx, lbType, scope, character, limit, offset
func (_m *LeaderboardUsecase) GetLeaderboard(ctx context.Context, lbType string, scope string, character string, limit int, offset int) (*models.HollowWildsLeaderboardResponse, error) {
	ret := _m.Called(ctx, lbType, scope, character, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaderboard")
	}

	var r0 *models.HollowWildsLeaderboardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) (*models.HollowWildsLeaderboardResponse, error)); ok {
		return rf(ctx, lbType, scope, character, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) *models.HollowWildsLeaderboardResponse); ok {
		r0 = rf(ctx, lbType, scope, character, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.HollowWildsLeaderboardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int, int) error); ok {
		r1 = rf(ctx, lbType, scope, character, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlayerStats provides a mock function with given fields: ctx, playerID
func (_m *LeaderboardUsecase) GetPlayerStats(ctx context.Context, playerID uuid.UUID) (*models.PlayerLeaderboardResponse, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayerStats")
	}

	var r0 *models.PlayerLeaderboardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.PlayerLeaderboardResponse, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.PlayerLeaderboardResponse); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PlayerLeaderboardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubmitEntry provides a mock function with given fields: ctx, playerID, req
func (_m *LeaderboardUsecase) SubmitEntry(ctx context.Context, playerID uuid.UUID, req models.LeaderboardSubmitRequest) (*models.LeaderboardSubmitResponse, error) {
	ret := _m.Called(ctx, playerID, req)

	if len(ret) == 0 {
		panic("no return value specified for SubmitEntry")
	}

	var r0 *models.LeaderboardSubmitResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.LeaderboardSubmitRequest) (*models.LeaderboardSubmitResponse, error)); ok {
		return rf(ctx, playerID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.LeaderboardSubmitRequest) *models.LeaderboardSubmitResponse); ok {
		r0 = rf(ctx, playerID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LeaderboardSubmitResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.LeaderboardSubmitRequest) error); ok {
		r1 = rf(ctx, playerID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLeaderboardUsecase creates a new instance of LeaderboardUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeaderboardUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeaderboardUsecase {
	mock := &LeaderboardUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
