// Code generated by mockery v2.53.6. DO NOT EDIT.

package usecase_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockLeaderboardUsecase is an autogenerated mock type for the LeaderboardUsecase type
type MockLeaderboardUsecase struct {
	mock.Mock
}

type MockLeaderboardUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLeaderboardUsecase) EXPECT() *MockLeaderboardUsecase_Expecter {
	return &MockLeaderboardUsecase_Expecter{mock: &_m.Mock}
}

// GetFriendsLeaderboard provides a mock function with given fields: ctx, userID, levelID
func (_m *MockLeaderboardUsecase) GetFriendsLeaderboard(ctx context.Context, userID uuid.UUID, levelID string) (*models.LevelLeaderboardResponse, error) {
	ret := _m.Called(ctx, userID, levelID)

	if len(ret) == 0 {
		panic("no return value specified for GetFriendsLeaderboard")
	}

	var r0 *models.LevelLeaderboardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*models.LevelLeaderboardResponse, error)); ok {
		return rf(ctx, userID, levelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *models.LevelLeaderboardResponse); ok {
		r0 = rf(ctx, userID, levelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LevelLeaderboardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, levelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLeaderboardUsecase_GetFriendsLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFriendsLeaderboard'
type MockLeaderboardUsecase_GetFriendsLeaderboard_Call struct {
	*mock.Call
}

// GetFriendsLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - levelID string
func (_e *MockLeaderboardUsecase_Expecter) GetFriendsLeaderboard(ctx interface{}, userID interface{}, levelID interface{}) *MockLeaderboardUsecase_GetFriendsLeaderboard_Call {
	return &MockLeaderboardUsecase_GetFriendsLeaderboard_Call{Call: _e.mock.On("GetFriendsLeaderboard", ctx, userID, levelID)}
}

func (_c *MockLeaderboardUsecase_GetFriendsLeaderboard_Call) Run(run func(ctx context.Context, userID uuid.UUID, levelID string)) *MockLeaderboardUsecase_GetFriendsLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockLeaderboardUsecase_GetFriendsLeaderboard_Call) Return(_a0 *models.LevelLeaderboardResponse, _a1 error) *MockLeaderboardUsecase_GetFriendsLeaderboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLeaderboardUsecase_GetFriendsLeaderboard_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*models.LevelLeaderboardResponse, error)) *MockLeaderboardUsecase_GetFriendsLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetGlobalLeaderboard provides a mock function with given fields: ctx, levelID, page, perPage
func (_m *MockLeaderboardUsecase) GetGlobalLeaderboard(ctx context.Context, levelID string, page int, perPage int) (*models.GlobalLeaderboardResponse, error) {
	ret := _m.Called(ctx, levelID, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalLeaderboard")
	}

	var r0 *models.GlobalLeaderboardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (*models.GlobalLeaderboardResponse, error)); ok {
		return rf(ctx, levelID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) *models.GlobalLeaderboardResponse); ok {
		r0 = rf(ctx, levelID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GlobalLeaderboardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, levelID, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLeaderboardUsecase_GetGlobalLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGlobalLeaderboard'
type MockLeaderboardUsecase_GetGlobalLeaderboard_Call struct {
	*mock.Call
}

// GetGlobalLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - levelID string
//   - page int
//   - perPage int
func (_e *MockLeaderboardUsecase_Expecter) GetGlobalLeaderboard(ctx interface{}, levelID interface{}, page interface{}, perPage interface{}) *MockLeaderboardUsecase_GetGlobalLeaderboard_Call {
	return &MockLeaderboardUsecase_GetGlobalLeaderboard_Call{Call: _e.mock.On("GetGlobalLeaderboard", ctx, levelID, page, perPage)}
}

func (_c *MockLeaderboardUsecase_GetGlobalLeaderboard_Call) Run(run func(ctx context.Context, levelID string, page int, perPage int)) *MockLeaderboardUsecase_GetGlobalLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockLeaderboardUsecase_GetGlobalLeaderboard_Call) Return(_a0 *models.GlobalLeaderboardResponse, _a1 error) *MockLeaderboardUsecase_GetGlobalLeaderboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLeaderboardUsecase_GetGlobalLeaderboard_Call) RunAndReturn(run func(context.Context, string, int, int) (*models.GlobalLeaderboardResponse, error)) *MockLeaderboardUsecase_GetGlobalLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeaderboard provides a mock function with given fields: ctx, lbType, scope, character, limit, offset
func (_m *MockLeaderboardUsecase) GetLeaderboard(ctx context.Context, lbType string, scope string, character string, limit int, offset int) (*models.HollowWildsLeaderboardResponse, error) {
	ret := _m.Called(ctx, lbType, scope, character, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaderboard")
	}

	var r0 *models.HollowWildsLeaderboardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) (*models.HollowWildsLeaderboardResponse, error)); ok {
		return rf(ctx, lbType, scope, character, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) *models.HollowWildsLeaderboardResponse); ok {
		r0 = rf(ctx, lbType, scope, character, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.HollowWildsLeaderboardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int, int) error); ok {
		r1 = rf(ctx, lbType, scope, character, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLeaderboardUsecase_GetLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaderboard'
type MockLeaderboardUsecase_GetLeaderboard_Call struct {
	*mock.Call
}

// GetLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - lbType string
//   - scope string
//   - character string
//   - limit int
//   - offset int
func (_e *MockLeaderboardUsecase_Expecter) GetLeaderboard(ctx interface{}, lbType interface{}, scope interface{}, character interface{}, limit interface{}, offset interface{}) *MockLeaderboardUsecase_GetLeaderboard_Call {
	return &MockLeaderboardUsecase_GetLeaderboard_Call{Call: _e.mock.On("GetLeaderboard", ctx, lbType, scope, character, limit, offset)}
}

func (_c *MockLeaderboardUsecase_GetLeaderboard_Call) Run(run func(ctx context.Context, lbType string, scope string, character string, limit int, offset int)) *MockLeaderboardUsecase_GetLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *MockLeaderboardUsecase_GetLeaderboard_Call) Return(_a0 *models.HollowWildsLeaderboardResponse, _a1 error) *MockLeaderboardUsecase_GetLeaderboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLeaderboardUsecase_GetLeaderboard_Call) RunAndReturn(run func(context.Context, string, string, string, int, int) (*models.HollowWildsLeaderboardResponse, error)) *MockLeaderboardUsecase_GetLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlayerRank provides a mock function with given fields: ctx, userID, levelID
func (_m *MockLeaderboardUsecase) GetPlayerRank(ctx context.Context, userID uuid.UUID, levelID string) (*models.PlayerStatsResponse, error) {
	ret := _m.Called(ctx, userID, levelID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayerRank")
	}

	var r0 *models.PlayerStatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*models.PlayerStatsResponse, error)); ok {
		return rf(ctx, userID, levelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *models.PlayerStatsResponse); ok {
		r0 = rf(ctx, userID, levelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PlayerStatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, levelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLeaderboardUsecase_GetPlayerRank_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlayerRank'
type MockLeaderboardUsecase_GetPlayerRank_Call struct {
	*mock.Call
}

// GetPlayerRank is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - levelID string
func (_e *MockLeaderboardUsecase_Expecter) GetPlayerRank(ctx interface{}, userID interface{}, levelID interface{}) *MockLeaderboardUsecase_GetPlayerRank_Call {
	return &MockLeaderboardUsecase_GetPlayerRank_Call{Call: _e.mock.On("GetPlayerRank", ctx, userID, levelID)}
}

func (_c *MockLeaderboardUsecase_GetPlayerRank_Call) Run(run func(ctx context.Context, userID uuid.UUID, levelID string)) *MockLeaderboardUsecase_GetPlayerRank_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockLeaderboardUsecase_GetPlayerRank_Call) Return(_a0 *models.PlayerStatsResponse, _a1 error) *MockLeaderboardUsecase_GetPlayerRank_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLeaderboardUsecase_GetPlayerRank_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*models.PlayerStatsResponse, error)) *MockLeaderboardUsecase_GetPlayerRank_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlayerStats provides a mock function with given fields: ctx, playerID
func (_m *MockLeaderboardUsecase) GetPlayerStats(ctx context.Context, playerID uuid.UUID) (*models.PlayerLeaderboardResponse, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayerStats")
	}

	var r0 *models.PlayerLeaderboardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.PlayerLeaderboardResponse, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.PlayerLeaderboardResponse); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PlayerLeaderboardResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLeaderboardUsecase_GetPlayerStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlayerStats'
type MockLeaderboardUsecase_GetPlayerStats_Call struct {
	*mock.Call
}

// GetPlayerStats is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockLeaderboardUsecase_Expecter) GetPlayerStats(ctx interface{}, playerID interface{}) *MockLeaderboardUsecase_GetPlayerStats_Call {
	return &MockLeaderboardUsecase_GetPlayerStats_Call{Call: _e.mock.On("GetPlayerStats", ctx, playerID)}
}

func (_c *MockLeaderboardUsecase_GetPlayerStats_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockLeaderboardUsecase_GetPlayerStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockLeaderboardUsecase_GetPlayerStats_Call) Return(_a0 *models.PlayerLeaderboardResponse, _a1 error) *MockLeaderboardUsecase_GetPlayerStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLeaderboardUsecase_GetPlayerStats_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.PlayerLeaderboardResponse, error)) *MockLeaderboardUsecase_GetPlayerStats_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitEntry provides a mock function with given fields: ctx, playerID, req
func (_m *MockLeaderboardUsecase) SubmitEntry(ctx context.Context, playerID uuid.UUID, req models.LeaderboardSubmitRequest) (*models.LeaderboardSubmitResponse, error) {
	ret := _m.Called(ctx, playerID, req)

	if len(ret) == 0 {
		panic("no return value specified for SubmitEntry")
	}

	var r0 *models.LeaderboardSubmitResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.LeaderboardSubmitRequest) (*models.LeaderboardSubmitResponse, error)); ok {
		return rf(ctx, playerID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.LeaderboardSubmitRequest) *models.LeaderboardSubmitResponse); ok {
		r0 = rf(ctx, playerID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LeaderboardSubmitResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.LeaderboardSubmitRequest) error); ok {
		r1 = rf(ctx, playerID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLeaderboardUsecase_SubmitEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitEntry'
type MockLeaderboardUsecase_SubmitEntry_Call struct {
	*mock.Call
}

// SubmitEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
//   - req models.LeaderboardSubmitRequest
func (_e *MockLeaderboardUsecase_Expecter) SubmitEntry(ctx interface{}, playerID interface{}, req interface{}) *MockLeaderboardUsecase_SubmitEntry_Call {
	return &MockLeaderboardUsecase_SubmitEntry_Call{Call: _e.mock.On("SubmitEntry", ctx, playerID, req)}
}

func (_c *MockLeaderboardUsecase_SubmitEntry_Call) Run(run func(ctx context.Context, playerID uuid.UUID, req models.LeaderboardSubmitRequest)) *MockLeaderboardUsecase_SubmitEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.LeaderboardSubmitRequest))
	})
	return _c
}

func (_c *MockLeaderboardUsecase_SubmitEntry_Call) Return(_a0 *models.LeaderboardSubmitResponse, _a1 error) *MockLeaderboardUsecase_SubmitEntry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLeaderboardUsecase_SubmitEntry_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.LeaderboardSubmitRequest) (*models.LeaderboardSubmitResponse, error)) *MockLeaderboardUsecase_SubmitEntry_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEntry provides a mock function with given fields: ctx, userID, levelID, timeSeconds, stars
func (_m *MockLeaderboardUsecase) UpdateEntry(ctx context.Context, userID uuid.UUID, levelID string, timeSeconds float64, stars int) error {
	ret := _m.Called(ctx, userID, levelID, timeSeconds, stars)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, float64, int) error); ok {
		r0 = rf(ctx, userID, levelID, timeSeconds, stars)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLeaderboardUsecase_UpdateEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEntry'
type MockLeaderboardUsecase_UpdateEntry_Call struct {
	*mock.Call
}

// UpdateEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - levelID string
//   - timeSeconds float64
//   - stars int
func (_e *MockLeaderboardUsecase_Expecter) UpdateEntry(ctx interface{}, userID interface{}, levelID interface{}, timeSeconds interface{}, stars interface{}) *MockLeaderboardUsecase_UpdateEntry_Call {
	return &MockLeaderboardUsecase_UpdateEntry_Call{Call: _e.mock.On("UpdateEntry", ctx, userID, levelID, timeSeconds, stars)}
}

func (_c *MockLeaderboardUsecase_UpdateEntry_Call) Run(run func(ctx context.Context, userID uuid.UUID, levelID string, timeSeconds float64, stars int)) *MockLeaderboardUsecase_UpdateEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(float64), args[4].(int))
	})
	return _c
}

func (_c *MockLeaderboardUsecase_UpdateEntry_Call) Return(_a0 error) *MockLeaderboardUsecase_UpdateEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLeaderboardUsecase_UpdateEntry_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, float64, int) error) *MockLeaderboardUsecase_UpdateEntry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLeaderboardUsecase creates a new instance of MockLeaderboardUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLeaderboardUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLeaderboardUsecase {
	mock := &MockLeaderboardUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
