// Code generated by mockery v2.53.6. DO NOT EDIT.

package usecase_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockLevelUsecase is an autogenerated mock type for the LevelUsecase type
type MockLevelUsecase struct {
	mock.Mock
}

type MockLevelUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLevelUsecase) EXPECT() *MockLevelUsecase_Expecter {
	return &MockLevelUsecase_Expecter{mock: &_m.Mock}
}

// CompleteLevel provides a mock function with given fields: ctx, userID, req
func (_m *MockLevelUsecase) CompleteLevel(ctx context.Context, userID uuid.UUID, req *models.LevelCompletionRequest) (*models.LevelCompletionResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CompleteLevel")
	}

	var r0 *models.LevelCompletionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *models.LevelCompletionRequest) (*models.LevelCompletionResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *models.LevelCompletionRequest) *models.LevelCompletionResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LevelCompletionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *models.LevelCompletionRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLevelUsecase_CompleteLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteLevel'
type MockLevelUsecase_CompleteLevel_Call struct {
	*mock.Call
}

// CompleteLevel is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req *models.LevelCompletionRequest
func (_e *MockLevelUsecase_Expecter) CompleteLevel(ctx interface{}, userID interface{}, req interface{}) *MockLevelUsecase_CompleteLevel_Call {
	return &MockLevelUsecase_CompleteLevel_Call{Call: _e.mock.On("CompleteLevel", ctx, userID, req)}
}

func (_c *MockLevelUsecase_CompleteLevel_Call) Run(run func(ctx context.Context, userID uuid.UUID, req *models.LevelCompletionRequest)) *MockLevelUsecase_CompleteLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*models.LevelCompletionRequest))
	})
	return _c
}

func (_c *MockLevelUsecase_CompleteLevel_Call) Return(_a0 *models.LevelCompletionResponse, _a1 error) *MockLevelUsecase_CompleteLevel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLevelUsecase_CompleteLevel_Call) RunAndReturn(run func(context.Context, uuid.UUID, *models.LevelCompletionRequest) (*models.LevelCompletionResponse, error)) *MockLevelUsecase_CompleteLevel_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLevelUsecase creates a new instance of MockLevelUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLevelUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLevelUsecase {
	mock := &MockLevelUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
