// Code generated by mockery v2.53.6. DO NOT EDIT.

package usecase_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPlayerUsecase is an autogenerated mock type for the PlayerUsecase type
type MockPlayerUsecase struct {
	mock.Mock
}

type MockPlayerUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlayerUsecase) EXPECT() *MockPlayerUsecase_Expecter {
	return &MockPlayerUsecase_Expecter{mock: &_m.Mock}
}

// CreateBackup provides a mock function with given fields: ctx, playerID
func (_m *MockPlayerUsecase) CreateBackup(ctx context.Context, playerID uuid.UUID) (*models.PlayerSaveBackup, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for CreateBackup")
	}

	var r0 *models.PlayerSaveBackup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.PlayerSaveBackup, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.PlayerSaveBackup); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PlayerSaveBackup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlayerUsecase_CreateBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBackup'
type MockPlayerUsecase_CreateBackup_Call struct {
	*mock.Call
}

// CreateBackup is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockPlayerUsecase_Expecter) CreateBackup(ctx interface{}, playerID interface{}) *MockPlayerUsecase_CreateBackup_Call {
	return &MockPlayerUsecase_CreateBackup_Call{Call: _e.mock.On("CreateBackup", ctx, playerID)}
}

func (_c *MockPlayerUsecase_CreateBackup_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockPlayerUsecase_CreateBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPlayerUsecase_CreateBackup_Call) Return(_a0 *models.PlayerSaveBackup, _a1 error) *MockPlayerUsecase_CreateBackup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlayerUsecase_CreateBackup_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.PlayerSaveBackup, error)) *MockPlayerUsecase_CreateBackup_Call {
	_c.Call.Return(run)
	return _c
}

// GetBackups provides a mock function with given fields: ctx, playerID
func (_m *MockPlayerUsecase) GetBackups(ctx context.Context, playerID uuid.UUID) ([]models.PlayerSaveBackup, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetBackups")
	}

	var r0 []models.PlayerSaveBackup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.PlayerSaveBackup, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.PlayerSaveBackup); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PlayerSaveBackup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlayerUsecase_GetBackups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBackups'
type MockPlayerUsecase_GetBackups_Call struct {
	*mock.Call
}

// GetBackups is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockPlayerUsecase_Expecter) GetBackups(ctx interface{}, playerID interface{}) *MockPlayerUsecase_GetBackups_Call {
	return &MockPlayerUsecase_GetBackups_Call{Call: _e.mock.On("GetBackups", ctx, playerID)}
}

func (_c *MockPlayerUsecase_GetBackups_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockPlayerUsecase_GetBackups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPlayerUsecase_GetBackups_Call) Return(_a0 []models.PlayerSaveBackup, _a1 error) *MockPlayerUsecase_GetBackups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlayerUsecase_GetBackups_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.PlayerSaveBackup, error)) *MockPlayerUsecase_GetBackups_Call {
	_c.Call.Return(run)
	return _c
}

// GetSave provides a mock function with given fields: ctx, playerID
func (_m *MockPlayerUsecase) GetSave(ctx context.Context, playerID uuid.UUID) (*models.PlayerSave, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetSave")
	}

	var r0 *models.PlayerSave
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.PlayerSave, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.PlayerSave); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PlayerSave)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlayerUsecase_GetSave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSave'
type MockPlayerUsecase_GetSave_Call struct {
	*mock.Call
}

// GetSave is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
func (_e *MockPlayerUsecase_Expecter) GetSave(ctx interface{}, playerID interface{}) *MockPlayerUsecase_GetSave_Call {
	return &MockPlayerUsecase_GetSave_Call{Call: _e.mock.On("GetSave", ctx, playerID)}
}

func (_c *MockPlayerUsecase_GetSave_Call) Run(run func(ctx context.Context, playerID uuid.UUID)) *MockPlayerUsecase_GetSave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPlayerUsecase_GetSave_Call) Return(_a0 *models.PlayerSave, _a1 error) *MockPlayerUsecase_GetSave_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlayerUsecase_GetSave_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.PlayerSave, error)) *MockPlayerUsecase_GetSave_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreFromBackup provides a mock function with given fields: ctx, playerID, backupID
func (_m *MockPlayerUsecase) RestoreFromBackup(ctx context.Context, playerID uuid.UUID, backupID uuid.UUID) (*models.PlayerSave, error) {
	ret := _m.Called(ctx, playerID, backupID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreFromBackup")
	}

	var r0 *models.PlayerSave
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*models.PlayerSave, error)); ok {
		return rf(ctx, playerID, backupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *models.PlayerSave); ok {
		r0 = rf(ctx, playerID, backupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PlayerSave)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID, backupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlayerUsecase_RestoreFromBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreFromBackup'
type MockPlayerUsecase_RestoreFromBackup_Call struct {
	*mock.Call
}

// RestoreFromBackup is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
//   - backupID uuid.UUID
func (_e *MockPlayerUsecase_Expecter) RestoreFromBackup(ctx interface{}, playerID interface{}, backupID interface{}) *MockPlayerUsecase_RestoreFromBackup_Call {
	return &MockPlayerUsecase_RestoreFromBackup_Call{Call: _e.mock.On("RestoreFromBackup", ctx, playerID, backupID)}
}

func (_c *MockPlayerUsecase_RestoreFromBackup_Call) Run(run func(ctx context.Context, playerID uuid.UUID, backupID uuid.UUID)) *MockPlayerUsecase_RestoreFromBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockPlayerUsecase_RestoreFromBackup_Call) Return(_a0 *models.PlayerSave, _a1 error) *MockPlayerUsecase_RestoreFromBackup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlayerUsecase_RestoreFromBackup_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*models.PlayerSave, error)) *MockPlayerUsecase_RestoreFromBackup_Call {
	_c.Call.Return(run)
	return _c
}

// SaveGame provides a mock function with given fields: ctx, playerID, saveData, expectedVersion
func (_m *MockPlayerUsecase) SaveGame(ctx context.Context, playerID uuid.UUID, saveData models.GameSaveData, expectedVersion int) (*models.PlayerSave, error) {
	ret := _m.Called(ctx, playerID, saveData, expectedVersion)

	if len(ret) == 0 {
		panic("no return value specified for SaveGame")
	}

	var r0 *models.PlayerSave
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.GameSaveData, int) (*models.PlayerSave, error)); ok {
		return rf(ctx, playerID, saveData, expectedVersion)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.GameSaveData, int) *models.PlayerSave); ok {
		r0 = rf(ctx, playerID, saveData, expectedVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PlayerSave)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.GameSaveData, int) error); ok {
		r1 = rf(ctx, playerID, saveData, expectedVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlayerUsecase_SaveGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveGame'
type MockPlayerUsecase_SaveGame_Call struct {
	*mock.Call
}

// SaveGame is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID uuid.UUID
//   - saveData models.GameSaveData
//   - expectedVersion int
func (_e *MockPlayerUsecase_Expecter) SaveGame(ctx interface{}, playerID interface{}, saveData interface{}, expectedVersion interface{}) *MockPlayerUsecase_SaveGame_Call {
	return &MockPlayerUsecase_SaveGame_Call{Call: _e.mock.On("SaveGame", ctx, playerID, saveData, expectedVersion)}
}

func (_c *MockPlayerUsecase_SaveGame_Call) Run(run func(ctx context.Context, playerID uuid.UUID, saveData models.GameSaveData, expectedVersion int)) *MockPlayerUsecase_SaveGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.GameSaveData), args[3].(int))
	})
	return _c
}

func (_c *MockPlayerUsecase_SaveGame_Call) Return(_a0 *models.PlayerSave, _a1 error) *MockPlayerUsecase_SaveGame_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlayerUsecase_SaveGame_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.GameSaveData, int) (*models.PlayerSave, error)) *MockPlayerUsecase_SaveGame_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPlayerUsecase creates a new instance of MockPlayerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlayerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlayerUsecase {
	mock := &MockPlayerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
