// Code generated by mockery v2.53.6. DO NOT EDIT.

package usecase_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PlayerUsecase is an autogenerated mock type for the PlayerUsecase type
type PlayerUsecase struct {
	mock.Mock
}

// CreateBackup provides a mock function with given fields: ctx, playerID
func (_m *PlayerUsecase) CreateBackup(ctx context.Context, playerID uuid.UUID) (*models.PlayerSaveBackup, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for CreateBackup")
	}

	var r0 *models.PlayerSaveBackup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.PlayerSaveBackup, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.PlayerSaveBackup); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PlayerSaveBackup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBackups provides a mock function with given fields: ctx, playerID
func (_m *PlayerUsecase) GetBackups(ctx context.Context, playerID uuid.UUID) ([]models.PlayerSaveBackup, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetBackups")
	}

	var r0 []models.PlayerSaveBackup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.PlayerSaveBackup, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.PlayerSaveBackup); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PlayerSaveBackup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSave provides a mock function with given fields: ctx, playerID
func (_m *PlayerUsecase) GetSave(ctx context.Context, playerID uuid.UUID) (*models.PlayerSave, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetSave")
	}

	var r0 *models.PlayerSave
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.PlayerSave, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.PlayerSave); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PlayerSave)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveGame provides a mock function with given fields: ctx, playerID, saveData, expectedVersion
func (_m *PlayerUsecase) SaveGame(ctx context.Context, playerID uuid.UUID, saveData models.GameSaveData, expectedVersion int) (*models.PlayerSave, error) {
	ret := _m.Called(ctx, playerID, saveData, expectedVersion)

	if len(ret) == 0 {
		panic("no return value specified for SaveGame")
	}

	var r0 *models.PlayerSave
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.GameSaveData, int) (*models.PlayerSave, error)); ok {
		return rf(ctx, playerID, saveData, expectedVersion)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.GameSaveData, int) *models.PlayerSave); ok {
		r0 = rf(ctx, playerID, saveData, expectedVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PlayerSave)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.GameSaveData, int) error); ok {
		r1 = rf(ctx, playerID, saveData, expectedVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPlayerUsecase creates a new instance of PlayerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlayerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlayerUsecase {
	mock := &PlayerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
