// Code generated by mockery v2.53.6. DO NOT EDIT.

package usecase_mock

import (
	context "context"

	models "github.com/NhomNhem/HollowWilds-Backend/internal/domain/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTalentUsecase is an autogenerated mock type for the TalentUsecase type
type MockTalentUsecase struct {
	mock.Mock
}

type MockTalentUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTalentUsecase) EXPECT() *MockTalentUsecase_Expecter {
	return &MockTalentUsecase_Expecter{mock: &_m.Mock}
}

// GetTalentConfigs provides a mock function with no fields
func (_m *MockTalentUsecase) GetTalentConfigs() map[string]*models.TalentConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTalentConfigs")
	}

	var r0 map[string]*models.TalentConfig
	if rf, ok := ret.Get(0).(func() map[string]*models.TalentConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*models.TalentConfig)
		}
	}

	return r0
}

// MockTalentUsecase_GetTalentConfigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTalentConfigs'
type MockTalentUsecase_GetTalentConfigs_Call struct {
	*mock.Call
}

// GetTalentConfigs is a helper method to define mock.On call
func (_e *MockTalentUsecase_Expecter) GetTalentConfigs() *MockTalentUsecase_GetTalentConfigs_Call {
	return &MockTalentUsecase_GetTalentConfigs_Call{Call: _e.mock.On("GetTalentConfigs")}
}

func (_c *MockTalentUsecase_GetTalentConfigs_Call) Run(run func()) *MockTalentUsecase_GetTalentConfigs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTalentUsecase_GetTalentConfigs_Call) Return(_a0 map[string]*models.TalentConfig) *MockTalentUsecase_GetTalentConfigs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTalentUsecase_GetTalentConfigs_Call) RunAndReturn(run func() map[string]*models.TalentConfig) *MockTalentUsecase_GetTalentConfigs_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserTalents provides a mock function with given fields: ctx, userID
func (_m *MockTalentUsecase) GetUserTalents(ctx context.Context, userID uuid.UUID) ([]models.UserTalent, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTalents")
	}

	var r0 []models.UserTalent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.UserTalent, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.UserTalent); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserTalent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTalentUsecase_GetUserTalents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserTalents'
type MockTalentUsecase_GetUserTalents_Call struct {
	*mock.Call
}

// GetUserTalents is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTalentUsecase_Expecter) GetUserTalents(ctx interface{}, userID interface{}) *MockTalentUsecase_GetUserTalents_Call {
	return &MockTalentUsecase_GetUserTalents_Call{Call: _e.mock.On("GetUserTalents", ctx, userID)}
}

func (_c *MockTalentUsecase_GetUserTalents_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTalentUsecase_GetUserTalents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTalentUsecase_GetUserTalents_Call) Return(_a0 []models.UserTalent, _a1 error) *MockTalentUsecase_GetUserTalents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTalentUsecase_GetUserTalents_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.UserTalent, error)) *MockTalentUsecase_GetUserTalents_Call {
	_c.Call.Return(run)
	return _c
}

// UpgradeTalent provides a mock function with given fields: ctx, userID, talentID
func (_m *MockTalentUsecase) UpgradeTalent(ctx context.Context, userID uuid.UUID, talentID string) (*models.TalentUpgradeResponse, error) {
	ret := _m.Called(ctx, userID, talentID)

	if len(ret) == 0 {
		panic("no return value specified for UpgradeTalent")
	}

	var r0 *models.TalentUpgradeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*models.TalentUpgradeResponse, error)); ok {
		return rf(ctx, userID, talentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *models.TalentUpgradeResponse); ok {
		r0 = rf(ctx, userID, talentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TalentUpgradeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, talentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTalentUsecase_UpgradeTalent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpgradeTalent'
type MockTalentUsecase_UpgradeTalent_Call struct {
	*mock.Call
}

// UpgradeTalent is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - talentID string
func (_e *MockTalentUsecase_Expecter) UpgradeTalent(ctx interface{}, userID interface{}, talentID interface{}) *MockTalentUsecase_UpgradeTalent_Call {
	return &MockTalentUsecase_UpgradeTalent_Call{Call: _e.mock.On("UpgradeTalent", ctx, userID, talentID)}
}

func (_c *MockTalentUsecase_UpgradeTalent_Call) Run(run func(ctx context.Context, userID uuid.UUID, talentID string)) *MockTalentUsecase_UpgradeTalent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockTalentUsecase_UpgradeTalent_Call) Return(_a0 *models.TalentUpgradeResponse, _a1 error) *MockTalentUsecase_UpgradeTalent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTalentUsecase_UpgradeTalent_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*models.TalentUpgradeResponse, error)) *MockTalentUsecase_UpgradeTalent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTalentUsecase creates a new instance of MockTalentUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTalentUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTalentUsecase {
	mock := &MockTalentUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
